export default {
  accountChangeForm: {
    accountChangeForm: "FORMULIR PERUBAHAN AKUN",
    account: "账号",
    type: "TIPE",
    newValue: "ANGKA BARU",
    oldValue: "ANGKA LAMA",
    selectKeyShow20time: "Cukup masukkan kata kunci sebelum 20,",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    selectDateRange: "选择日期范围",
    selectGroup: "请选择分组",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  accountChangeList: {
    accountChangeList: "员工调整",
    id: "ID",
    areaName: "NAMA AREA",
    applyAccount: "FORMULIR LAMARAN",
    applyDate: "TANGGAL LAMARAN",
    type: "TIPE",
    oldValue: "sebelum modifikasi",
    newValue: "sesudah modifikasi",
    processStatus: "status proses",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    selectGroup: "请选择分类",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  accountForm: {
    accountForm: "FORMULIR AKUN",
    mainAccount: "AKUN UTAMA",
    loginName: "USERNAME",
    officeName: "DEPARTEMEN",
    depot: "绑定门店",
    leader: "pemimpin",
    position: "posisi",
    selectGroup: "pilih grup",
    dataScopeOffice: "departemen",
    viewReport: "Laporan Viewer",
    true: "beenar",
    false: "salah",
    outId: "ID",
    outPassword: "password",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  accountList: {
    accountList: "Manajemen akun",
    id: "ID",
    type: "tipe",
    loginName: "username",
    employeeName: "nama karyawan",
    leader: "pemimpin",
    officeName: "departemmen",
    dataScopeOffice: "departemen",
    depotName: "daftar deposit",
    positionName: "posisi",
    positionDataScope: "data lokasi",
    viewReport: "lihat laporan",
    selectGroup: "pilih grup",
    employeeStatus: "是否在职",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  accountTaskList: {
    accountTaskList: "待办事项",
    id: "ID",
    name: "nama",
    status: "status proses",
    lastModified: "terakhir update",
    lastModifiedDate: "terakhi tanggal update",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  auditFileDetail: {
    auditFileDetail: "Rincian persetujuan dokumen",
    createdBy: "dibuat oleh",
    createdDate: "dibuat pd tgl",
    id: "ID",
    title: "judul",
    processStatus: "status proses",
    remarks: "keterangan",
    attachment: "lampiran",
    isPass: "apakah sudah diapprove",
    comment: "komen",
    save: "simpan",
    stageName: "nama",
    auditMan: "periksa org",
    auditDate: "periksa tanggal",
    auditRemarks: "periksa keterangan",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "masukkAN ANGKA YANG VALID"
  },
  auditFileForm: {
    auditFileForm: "periksan formulir berkas",
    processTypeName: "nama tipe proses",
    title: "judul",
    auditFileRemarks: "keterangan",
    attachment: "lampiran",
    clickUpload: "klik unduh",
    uploadImageSizeFor5000KB: "unggah foto dibawah 500kb",
    content: "konten",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  auditFileList: {
    auditFileList: "Dokumen persetujuan",
    id: "ID",
    auditType: "jenis pemeriksaan",
    applyAccount: "formulir akun",
    areaName: "nama area",
    officeName: "申请部门",
    officeId: "departemen",
    processTypeName: "nama tipe proses",
    title: "judul",
    processStatus: "status proses",
    memo: "memo",
    stageName: "nama",
    content: "konten",
    all: "semua departemen",
    waitAudit: "menunggu pemeriksaan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    notZero: "输入非零部分",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutyAnnualForm: {
    dutyAnnualForm: "formulir tahunan",
    exportTemplate: "ekspor template",
    downLoad: "unduh",
    exportData: "ekspor data",
    clickUpload: "klik unduh",
    annualYear: "tahunan",
    selectAnnualYear: "pilih tahunan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  dutyAnnualList: {
    dutyAnnualList: "daftar tahunan",
    officeName: "departemen",
    positionName: "nama posisi",
    employeeName: "nama karyawan",
    annualYear: "tahunan",
    hour: "时间",
    leftHour: "waktu yg tersisa",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutyFreeList: {
    dutyFreeList: "免打考勤",
    freeDate: "tanggal libur",
    dateType: "tipe tgl",
    dutyFreeRemarks: "alasan cuti",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah",
  },
  dutyLeaveList: {
    dutyLeaveList: "formulir cuti",
    dutyDate: "tgl",
    dateType: "jenis tgl",
    leaveType: "jenis cuti",
    remarks: "alasan cuti",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  dutyOvertimeList: {
    dutyOvertimeList: "formulir lembur",
    dutyDate: "tgl",
    timeStart: "waktu mulai",
    timeEnd: "waktu selesai",
    hour: "jam lembur",
    remarks: "keterangan",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutyPublicFreeList: {
    dutyPublicFreeList: "manajemen cuti",
    freeDate: "tgl",
    dateType: "jenis tanggal",
    status: "status",
    remarks: "keterangan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutyRestList: {
    dutyRestList: "formulir libur",
    dutyDate: "tgl",
    type: "tipe",
    dateType: "jenis tgl",
    timeStart: "tgl mulai",
    timeEnd: "tgl selesai",
    hour: "jam",
    dutyRestRemarks: "kebijakan hari libur",
    status: "atatus",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutySignList: {
    dutySignList: "daftar check",
    employeeName: "nama karyawan",
    dutyDate: "tanggal",
    week: "minggu",
    dutyTime: "waktu kerja",
    address: "alamat",
    uuid: "pin telepon",
    netType: "tipe",
    attachment: "lampiran",
    status: "status",
    officeName: "departemen",
    positionName: "nama posisi",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutyTaskForm: {
    dutyTaskForm: "Layanan editing persetujuan",
    dutyTaskType: "jenis Layanan editing persetujuan",
    applyAccount: "formulir karyawan",
    leaveType: "jenis cuti",
    dutyLeaveDate: "tanggal cuti",
    dateLeaveType: "tanggal",
    dutySignDate: "cek tanggal",
    dutySignTime: "cek waktu",
    signAddress: "cek alamat",
    attachment: "lampiran",
    dutyRepairDate: "tanggal kartu",
    dutyRepairTime: "tanggal waktu",
    dutyOverTimeDate: "tanggal lembur",
    OverTimeStart: "waktu mulai",
    OverTimeEnd: "waktu selesai",
    OverTimeHour: "waktu lembur",
    restType: "tipe cuti",
    dutyRestDate: "tanggal cuti",
    dateAnnualType: "tipe tanggal",
    restTimeStart: "waktu mulai",
    restTimeEnd: "waktu selsai",
    restHour: "berapa lama cutinya",
    freeDate: "tanggal",
    dateFreeType: "tipe waktu",
    isPass: "apakah sudah dikonfirmasi",
    auditRemarks: "keterangan pemeriksaan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  dutyTaskList: {
    dutyTaskList: "layanan persetujuan",
    batchPass: "saring",
    formatId: "jumlah",
    dutyType: "jenis",
    dutyDate: "tanggal",
    applyAccount: "formulir akun",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutyTripList: {
    dutyTripList: "formulir dinas",
    dateStart: "tanggal mulai",
    dateEnd: "tanggal selesai",
    reason: "alasan",
    status: "status",
    date: "tgl",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dutyWorktimeForm: {
    dutyWorktimeForm: "Pukulan Rekam Edit",
    yearMonth: "penilaian bulanan",
    selectMonth: "pilih bulan",
    importFile: "unduh ebrkas",
    clickUpload: "klik unggah",
    uploadImageSizeFor5000KB: "unggah foto di bawah 500kb",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  dutyWorktimeList: {
    dutyWorktimeList: "打卡记录",
    selectMonth: "pilih bulan",
    yearMonth: "penilaian bulanan",
    dutyDate: "tanggal",
    week: "minggu",
    dutyTime: "waktu",
    employeeName: "nama karyawan",
    type: "jenis",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  employeeEditForm: {
    loginName: "USERNAME",
    password: "kata sandi",
    confirmPassword: "确认密码",
    bankName: "nama bank",
    bankItem: "开户网点",
    outId: "ID",
    outPassword: "password",
    LeaveEmpty:"若不修改密码,请留空",
    name: "nama karyawan",
    sexLabel: "jenisn kelamin",
    man: "laki-laki",
    women: "perempuan",
    birthday: "tanggal lahir",
    school: "sekolah",
    major: "专业",
    education: "pendidikan",
    image: "lampiran",
    clickUpload: "klik unggah",
    uploadImageSizeFor5000KB: "unggah foto dibawah 500kb",
    save: "simpan",
    remarks: "keterangan / komen"
  },
  employeeForm: {
    employeeForm: "formulir karyawan",
    employeeName: "nama karyawan",
    education: "pendidikan",
    code: "kode",
    salary: "gaji",
    bankNumber: "nomor rekening",
    bankName: "nama bank",
    entryDate: "tanggal masuk",
    regularDate: "tanggal biasa",
    leaveDate: "tanggal selesai",
    school: "sekolah",
    idCard: "kartu identitas",
    mobilePhone: "nomor telepon",
    birthday: "tanggal lahir",
    sex: "jenisn kelamin",
    man: "laki-laki",
    women: "perempuan",
    origin: "aasal",
    salerName: "KETERANGAN",
    loginName: "username",
    office: "departemen",
    depotList: "daftar deposit",
    leader: "pemimpin",
    position: "nama posisi",
    dataScopeOffices: "departemen",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    selectGroup: "pilih grup",
    selectDate: "请选择时间",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  employeeList: {
    employeeList: "daftar karyawan",
    employeeName: "nama karyawan",
    sex: "jenis kelamin",
    depotList: "",
    officeName: "lembaga",
    positionName: "nama posisi",
    leader: "pemimpin",
    entryDate: "tanggal masuk",
    leaveDate: "tanggal keluar",
    status: "status",
    mobilePhone: "nomor hp",
    regularDate: "tanggal regular",
    selectGroup: "pilih grup",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  employeePhoneDepositForm: {
    employeePhoneDepositForm: "formulir deposit karyawan",
    employeeName: "nama karyawan",
    depotName: "nama toko",
    amount: "jumlah",
    department: "departemen",
    productName: "nama produk",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  employeePhoneDepositList: {
    employeePhoneDepositList: "daftar deposit karyawan",
    batchPass: "批量通过",
    batchNoPass: "批量打回",
    selectStatus: "pilih status",
    employeeName: "nama karyawan",
    shopName: "nama toko",
    areaName: "nama tempat",
    department: "departemen",
    bank: "bank",
    amount: "jumlah",
    outCode: "kode",
    billDate: "tanggal nota",
    productName: "nama produk",
    status: "status",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  employeePhoneForm: {
    employeePhoneForm: "edit mesin promotor",
    employeeName: "nama karyawan",
    depotName: "nama toko",
    depositAmount: "jumlah",
    uploadTime: "tanggal unduh",
    productName: "nama produk",
    jobPrice: "harga",
    retailPrice: "harga ecer",
    imeStr: "string kode",
    status: "status",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid,"
  },
  employeePhoneList: {
    employeePhoneList: "handphone promotor",
    employeePhoneDepositList: "daftar deposit karyawan",
    selectStatus: "pilih status",
    areaName: "nama tempat",
    depotName: "nama toko",
    employeeName: "nama karyawan",
    depositAmount: "jumlah",
    status: "status",
    uploadTime: "tanggal unduh",
    productName: "nama produk",
    jobPrice: "harga",
    imeStr: "string kode",
    retailPrice: "harga ecer",
    name: "姓名",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  jobForm: {
    jobForm: "formulir ppekerjaan",
    jobName: "nama pekerjaan",
    permission: "perizinan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  jobList: {
    jobList: "formulir ppekerjaan",
    jobName: "nama pekerjaan",
    permission: "perizinan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  officeForm: {
    officeForm: "formulir kantor",
    parentId: "atasan",
    officeName: "nama",
    type: "jenis",
    jointType: "tipe",
    point: "inti",
    taskPoint: "inti pekerjaan",
    sort: "pengurutan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang harus diisi",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  officeList: {
    officeList: "daftar kantor",
    parentName: "nama",
    name: "nama",
    typeLabel: "jenis label",
    dingId: "kode",
    point: "inti",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  positionForm: {
    positionForm: "formulir jabatan",
    jobId: "ID",
    name: "nama",
    reportName: "daftar nama",
    dataScope: "cakupan data",
    permission: "perizinan",
    sort: "pengurutan",
    permissionIdStr: "perizinan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  positionList: {
    positionList: "daftar jabatan",
    positionName: "nama posisi",
    jobName: "nama pekerjaan",
    dataScope: "cakupan data",
    permission: "perizinan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  recruitBatchForm: {
    recruitBatchForm:"招聘信息批量编辑",
    name: "nama",
    applyPositionName: "应聘岗位",
    applyFrom: "应聘来源",
    workArea: "工作地点",
    workCategory: "所属品类",
    education: "学历",
    entryRealDate: "入职实际时间",
  },
  recruitForm: {
    recruitForm: "formulir perekrutan",
    reserve: "预约",
    initialTest: "ujian",
    retest: "ujian ulang",
    auditStatus: "status pemeriksaan",
    entryJob: "semua pekerjaan",
    next: "selanjutnya",
    contactDate: "tanggal kontak",
    name: "nama",
    sex: "jenis kelamin",
    man: "laki-laki",
    women: "perempuan",
    mobilePhone: "nomor telepon",
    applyPositionId: "lamar jabatan",
    selectPosition: "pilih posisi",
    applyFrom: "formulir lamaran",
    firstAppointDate: "tanggal perjanjian pertama",
    selectFirstAppointDate: "pilih tanggal perjanjuan pertama",
    contactById: "hubungi dengan ID",
    selectContactById: "pilih kontak ID",
    firstRealDate: "tanggal pertama",
    workArea: "area kerja",
    workCategory: "kategori kerja",
    marriageStatus: "status perkawinan",
    birthday: "tanggal lahir",
    originSelectId: "asal",
    school: "sekolah",
    major: "jurusan",
    education: "pendidikan",
    firstBy: "dari",
    selectFirstBy: "pilih dari",
    firstPoint: "inti pertama",
    firstComment: "komen pertama",
    secondAppointDate: "tanggal perjanjian kedua",
    secondRealDate: "tanggal kedua",
    secondBy: "dari",
    selectSecondBy: "pilih dari",
    secondComment: "komen kedua",
    toStorage: "gudang",
    true: "benar",
    false: "salah",
    storageRemarks: "keterangan persediaan",
    physicalAppointDate: "tanggal perjanjian fisik",
    physicalRealDate: "tanggal fidik",
    auditAppointDate: "tanggal perjanjian pemeriksaan",
    auditRealDate: "tanggal pemeriksaan",
    entryAppointDate: "tanggal perjanjian masuk",
    entryRealDate: "tanggal perjanjian",
    idCard: "kartu identitas",
    unmarriedAndChildless: "未婚未育",
    marriedChildless: "已婚未育",
    marriedAlready: "已婚已育",
    other: "其它",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  recruitList: {
    recruitList: "daftar perekrutan",
    name: "nama",
    sex: "jenis kelamin",
    education: "pendidikan",
    mobilePhone: "nomor telepon",
    firstAppointDate: "初试时间",
    secondAppointDate: "复试时间",
    physicalAppointDate: "资审时间",
    add: "tambah",
    batchEdit: "批量修改",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
}
