export default {
  adApplyBillForm: {
    adApplyBillForm: "formulir nota",
    billType: "jenis nota",
    selectInput: "pilih input",
    selectDate:"请选择日期",
    billDate: "tanggal nota",
    expressCompany: "perusahaan jasa pengiriman",
    billRemarks: "keterangan nota",
    financeQty: "persediaan",
    shopName: "nama toko",
    productCode: "kode produk",
    productName: "nama produk",
    createdDate: "dibuat pada tanggal",
    applyQty: "kuantitas",
    confirmQty: "periksa kuantitas",
    leftQty: "sisa persediaan",
    billQty: "jumlah nota",
    price: "harga",
    save:"保存",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid",
    search: "搜索",
    inputTowKey: "至少二位关键字",
  },
  adApplyForm: {
    adApplyForm: "formulir bahan",
    billType: "jenis nota",
    shopName: "nama toko",
    shopType: "jenis toko",
    productCode: "编号",
    applyQty: "kuantitas",
    productName: "nama produk",
    expiryDateRemarks: "tanggal keterangan jatuh tempo",
    price2: "harga",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencaarian",
    selectInput: "请输入选择",
    search: "搜索",
    inputTowKey: "至少二位关键字",
    remarks: "keterangan",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang harus diisi",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  adApplyGoods: {
    adApplyGoods: "POP分货",
    productName: "pop货品",
    shopName: "门店",
    applyQty: "分货数量",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    selectInput: "请输入选择",
    search: "搜索",
    inputTowKey: "至少二位关键字",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  adApplyList: {
    adApplyList: "daftar bahan",
    adApplyForm: "formulir bahan",
    adApplyBillForm: "formulir nota",
    adApplyGoods: "POP分货",
    shopName: "nama toko",
    productCode: "kode",
    expiryDateRemarks: "tanggal keterangan jatuh tempo",
    shopType: "nama toko",
    product: "produk",
    applyQty: "kuantitas",
    confirmQty: "periksa kuantitas",
    billedQty: "jumlah",
    leftQty: "sisa persediaan",
    orderId: "nomor nota",
    remarks: "keterangan",
    createdBy: "dibuat oleh",
    createdDate: "dibuat pada tangga;",
    productName: "nama produk",
    isBilled: "apakah sudah di buka nota",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
  },
  adGoodsOrderBill: {
    adGoodsOrderBill: "buka nota bahan",
    code: "kode",
    billDate: "tanggal nota",
    outShopName: "buka nota toko",
    shopName: "nama toko",
    saleContact: "kontak sales",
    address: "alamat",
    summery: "ringkasan",
    adStore: "toko",
    contact: "kontak",
    mobilePhone: "nonor telepon",
    expressCompany: "perusahaan jasa pengiriman",
    splitBill: "nota terpisah",
    synToCloud: "SINKRONISASI",
    billRemarks: "keterangan nota",
    inputTwoKey: "masukkan 2 kata kunci",
    productName: "nama produk",
    stock: "persediaan",
    confirmQty: "确定数",
    billQty: "jumlah",
    price: "harga"
  },
  adGoodsOrderDetail: {
    adGoodsOrderDetail: "perincian bahan",
    orderCode: "nomor order",
    billDate: "tanggal nota",
    outShopName: "nama toko",
    shopName: "alamat toko",
    threeMonthQty: "kuantitas 3 bulan",
    employeeId: "ID karyawan",
    processStatus: "status",
    expressCodes: "kode pengiriman",
    createdBy: "username",
    remarks: "keterangan",
    contact: "kontak",
    address: "alamat",
    mobilePhone: "nomor telepon",
    pass: "saring",
    comment: "keterangan",
    audit: "periksa",
    code: "kode",
    productName: "nama produk",
    qty: "kuantu=itas",
    confirmQty: "jumlah",
    billQty: "jumlah nota",
    shippedQty: "jumlah pengiriman",
    price: "harga"
  },
  adGoodsOrderForm: {
    adGoodsOrderForm: "orderan etalase",
    outShopId: "nama toko",
    employeeName: "nama karyawan",
    expressCompany: "perusahaan jasa pengiriman",
    address: "alamat",
    contact: "kontak",
    mobilePhone: "nomor rekening",
    summery: "ringkasan",
    totalQty: "jumlah nota",
    totalAmount: "jumlah order",
    save: "simpan",
    filter: "saring",
    inputTwoKey: "masukkan 2 kata kunci",
    code: "kode",
    qty: "kuantitas",
    productName: "nama toko",
    price: "harga",
    remarks: "keterangan",
    inputWord:"请输入关键词",
    loading:"拼命加载中",
    prerequisiteMessage: "informasi yang harus diisi",
    inputLegalValue: "masukkan angka yang valid",
    selectKeyShow20time: "请输入关键词,显示前20条",
  },
  adGoodsOrderList: {
    adGoodsOrderList: "pemesanan etalase",
    add: "tambah",
    filter: "saring",
    blankOrComma: "kosong atau koma",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "masukkan kata kunci",
    inputWord: "masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    orderCode: "nomor order",
    createdDate: "dibuat pada tangga;",
    billDate: "tanggal nota",
    type: "tipe",
    outCode: "kode",
    processStatus: "status",
    storeName: "nama gudang",
    officeName: "nama kantor",
    areaName: "nama area",
    areaType: "nama tempat",
    shopName: "nama toko",
    amount: "jumlah",
    expressCodes: "kode resi",
    remarks: "keterangan",
    createdBy: "username",
    operation: "operasi",
    billType: "jenis",
    parentId: "ID",
    loading: "memuat"
  },
  adGoodsOrderShip: {
    adGoodsOrderShip: "order bahan",
    shipCode: "nomor order",
    remarks: "keterangan",
    smallQty: "kuantitas kecil",
    mediumQty: "kuantitas sedang",
    largeQty: "kuantitas besar",
    expressCodes: "kode resi",
    expressCompany: "perusahaan jasa pengiriman",
    ship: "pengiriman",
    shipShopName: "nota toko",
    saleContact: "kontak sales",
    saleMobile: "nomor telepon sales",
    billRemarks: "keterangan",
    contact: "kontak",
    address: "alamat",
    mobilePhone: "nomor telepon",
    shouldPay: "bayar",
    shouldGet: "dapat",
    realPay: "pembayaran sebenarnya",
    code: "kode",
    productName: "nama produk",
    billQty: "kuantitas",
    shippedQty: "jumolah pengiriman",
    waitShipQty: "menunggu pengiriman",
    shipQty: "jumlah pengiriman",
    nodeName: "nama",
    auditMan: "orang pemeriksaaan",
    auditDate: "tanggal audit",
    auditRemarks: "keterangan pemeriksaan"
  },
  adGoodsOrderSign: {
    adGoodsOrderSign: "order barang",
    orderId: "nomor barang",
    orderRemarks: "keterangan",
    outShopName: "nota toko",
    shopName: "nama toko",
    expressCodes: "kode resi",
    billRemarks: "keterangan",
    createdByName: "dibuat oleh",
    createdDate: "dibuat pada tanggal",
    billDate: "tanggal nota",
    materialSignIn: "bahan",
    code: "kode",
    productName: "nama produk",
    orderQty: "kuantitas",
    confirmQty: "jumlah",
    billQty: "jumlah nota",
    shippedQty: "jumlah"
  },
  adPricesystemChangeForm: {
    adPricesystemChangeForm: "formulir",
    id: "ID",
    productName: "nama",
    productCode: "kode",
    volume: "volume",
    shouldGet: "dapat",
    materialA: "bahamn 1",
    materialB: "bahan b",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  adPricesystemChangeList: {
    adPricesystemChangeList: "Pengiriman Edit",
    productName: "nama produk",
    productCode: "kode produk",
    adPricesystem: "sistem harga",
    oldPrice: "harga lama",
    newPrice: "harga baru",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopAdForm: {
    shopAdForm: "formulir iklan",
    shopAdTypeId: "nama iklan",
    shopId: "toko",
    length: "panjang",
    width: "lebar",
    qty: "kuantitas",
    content: "konten",
    specialArea: "area",
    attachment: "lampiran",
    clickUpload: "klik unggah",
    uploadImageSizeFor5000KB: "unggah foto dibawah 500kb",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopAdList: {
    shopAdList: "formulir iklan",
    batchPass: "konfirmasi",
    batchBlack: "kembali",
    code: "kode",
    areaName: "lebar",
    shopName: "toko",
    specialArea: "daerah",
    shopAdType: "nama iklan",
    lengthAndWidthAndQty: "panjanng dan lebar dan kuantitas",
    totalArea: "total area",
    price: "harga",
    content: "konten",
    processStatus: "status",
    adCode: "kode iklan",
    isSpecialArea: "area",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopAdDetail: {
    shopAdDetail: "formulir iklan",
    shopAdTypeId: "nama iklan",
    shopId: "toko",
    length: "panjang",
    width: "lebar",
    qty: "kuantitas",
    content: "konten",
    specialArea: "area",
    remarks: "keterangan",
    attachment: "lampiran",
    nodeName: "nama,",
    auditMan: "orang pemeriksaan",
    auditDate: "tanggal pemeriksaan",
    auditRemarks: "keterangan pemeriksaan"
  },
  shopAllotDetail: {
    shopAllotDetail: "Toko alokasi editing",
    billCode: "kode nota",
    status: "status",
    outSaleCode: "kode barang keluar",
    outReturnCode: "kode barang returan",
    saleTotalPrice: "nominal nota",
    remarks: "keterangan",
    fromShop: "sebelum transfer",
    toShop: "sesudah transfer",
    syn: "sinkronisasi",
    true: "benar",
    false: "salah",
    pass: "konfirmasi",
    auditRemarks: "keterangan pemeriksaan",
    save: "simpan",
    filter: "saring",
    productName: "nama produk",
    qty: "kuantitas",
    returnPrice: "harga returan",
    salePrice: "harga"
  },
  shopAllotForm: {
    shopAllotForm: "tambah alokasi toko",
    fromShop: "sebelum transfer",
    toShop: "sesudah transfer",
    productName: "nama produk",
    selectTowKey: "Setidaknya dua kunci",
    qty: "kuantitas",
    inputKey: "masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopAllotList: {
    shopAllotList: "alokasi toko",
    billCode: "kode nota",
    status: "status",
    outSaleCode: "kode nota",
    outReturnCode: "kode retur barang",
    fromShop: "sebelum transfer",
    toShop: "sesudah transfer",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    multiEnterOrComma: "Masukkan koma atau pluralitas spasi terpisah",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopBuildDetail: {
    shopBuildDetail: "Detail konstruksi toko",
    shopBuildCode: "nomor Detail konstruksi toko",
    office: "daerah",
    shopName: "toko",
    monthSaleQty: "门店近三个月销量",
    shopType: "kuantitas penjualan 3 bulan",
    address: "alamat",
    applyAccount: "sales",
    mobilePhone: "nomor telepon",
    remarks: "keterangan",
    fixtureType: "jenis fitur",
    oldContents: "konten lama",
    newContents: "konten baru",
    buildType: "informasi proyek",
    content: "konten",
    processStatus: "status",
    scenePhoto: "gambar",
    confirmPhoto: "konfirmasi gambar"
  },
  shopBuildForm: {
    shopBuildForm: "Mengedit konstruksi toko",
    shopId: "toko",
    shopType: "jenis toko",
    inputType: "pilih grup",
    fixtureType: "jenis fitur",
    oldContents: "konten lama",
    newContents: "konten baru",
    buildType: "informasi proyek",
    applyAccount: "sales",
    content: "konten",
    scenePhoto: "gambar",
    clickUpload: "pilih unggah",
    uploadImageSizeFor5000KB: "unggah foto dibawah 500kb",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopBuildList: {
    shopBuildList: "konstruksi toko",
    batchPass: "konfirmasi",
    batchBlack: "kembali",
    code: "kode",
    officeName: "nama kantor",
    shopName: "toko",
    fixtureType: "tipe fitur",
    oldContents: "konten lama",
    newContents: "konten baru",
    content: "konten",
    auditType: "jenis pemeriksaan",
    processFlow: "status persetujuan",
    all: "semua departemen",
    waitAudit: "menunggu persediaan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopDepositForm: {
    shopDepositForm: "daftar deposit",
    shopName: "toko",
    department: "部门",
    type: "jenis",
    amount: "jumlah",
    outBillType: "kode keluar",
    bank: "bank",
    inputBank: "pilih bank",
    marketAmount: "jumlah",
    imageAmount: "jumlah demo",
    demoPhoneAmount: "konten",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "请输入合法的数值",
  },
  shopDepositList: {
    shopDepositList: "daftar deposit",
    billCode: "kode nota",
    shopName: "toko",
    areaName: "nama area",
    officeName: "afiliasi",
    type: "jenis",
    amount: "jumlah",
    leftAmount: "sisa persediaan",
    outCode: "kode keluar",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopGoodsDepositForm: {
    shopGoodsDepositForm: "piutang deposit",
    bank: "bank",
    shopName: "toko",
    amount: "jumlah",
    department: "departemen",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopGoodsDepositList: {
    shopGoodsDepositList: "piutang deposit",
    batchPass: "konfirmasi",
    inputStatus: "pilih status",
    preciseSearch: "精确搜索",
    code: "kode",
    shopName: "toko",
    areaName: "nama area",
    department: "departemen",
    bank: "bank",
    amount: "jumlah",
    outBillType: "jenis nota",
    billDate: "tanggal buka nota",
    Deposit: "deposit",
    outCode: "kode keluar",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopImageForm: {
    shopImageForm: "Mengganti image editor",
    shopName: "toko",
    imageType: "jenis gambar",
    inputType: "pilih grup",
    imageSize: "ukuran gambar",
    image: "gambar",
    clickUpload: "klik unggah",
    uploadImageSizeFor5000KB: "",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopImageList: {
    shopImageList: "penggantian gambar",
    areaName: "nama area",
    officeName: "nama kantor",
    imageType: "jenis gambar",
    shopName: "toko",
    image: "gambar",
    imageSize: "ukuran gambar",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopPrintDetail: {
    shopPrintDetail: "perincian cetak periklanan",
    officeName: "area",
    printType: "jenis printer",
    code: "kode",
    content: "konten",
    attachment: "lampiran",
    address: "alamat",
    contact: "kontak",
    mobilePhone: "nomor telepon",
    nodeName: "nama",
    auditMan: "orang pemeriksaan",
    auditDate: "tanggal pemeriksaan",
    auditRemarks: "keterangan pemeriksaan",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    remarks: "keterangan / komen",
  },
  shopPrintForm: {
    shopPrintForm: "formulir cetak periklanan",
    officeName: "alamat",
    officeId: "ID",
    printType: "jenis printer",
    inputType: "pilih grup",
    content: "konten",
    qty: "kuantitas",
    address: "alamat",
    contact: "kontak",
    mobilePhone: "nomor telepon",
    attachment: "lampiran",
    clickUpload: "点击上传",
    uploadImageSizeFor5000KB: "unggah foto dibawah 500kb",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopPrintList: {
    shopPrintList: "cetak periklanan",
    code: "kode",
    officeId: "ID",
    qty: "kuantitas",
    address: "alamat",
    content: "konten",
    contact: "kontak",
    mobilePhone: "nomor telepon",
    printType: "jenis printer",
    processStatus: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopPromotionForm: {
    shopPromotionForm: "活动拉销编辑",
    shopId: "toko",
    activityDate: "tanggal",
    inputDate: "tanggal input",
    activityType: "tanggal aktivitas",
    inputType: "tanggal input",
    amount: "jumlah",
    dayAmount: "OPPO jumlah hari",
    salerComment: "keterangan",
    materialComment: "input bahan Deskripsi",
    comment: "Ringkasan Kegiatan Usaha",
    phone: "nomor telepon sales",
    activityImage1: "foto bahan",
    activityImage2: "foto wilayah",
    activityImage3: "Secara keseluruhan outfield diatur foto",
    clickUpload: "klik unggah",
    uploadImageSizeFor5000KB: "unggah foto dibawah 500kb",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopPromotionList: {
    shopPromotionList: "活动拉销",
    businessId: "kode nota",
    shopName: "toko",
    activityType: "kegiatan",
    amount: "jumlah",
    dayAmount: "OPPO jumlah hari",
    salerComment: "masukkan daftar staff",
    materialComment: "keterangan bahan",
    comment: "keterangan",
    phone: "nomor telepon sales",
    activityImage1: "foto bahan",
    activityImage2: "foto wilayah",
    activityImage3: "Secara keseluruhan outfield diatur foto",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
}
