export default {
  util:{
    true:"是",
    false:"否",
    today:"今天",
    yesterday:"昨天",
    latestWeek:"最近一周",
    latestMonth:"最近一个月",
    waringMsgBeforeDelRecord:"此操作将永久删除该记录, 是否继续?",
    typeOfWarningBeforeDelRecord:"提示",
    confirmButton:"确定",
    cancelButton:"取消",

  },
  head_tab: {
    home: "首页",
  },
  su_district:{
    inputKey:"请输入关键字",
  },
  su_table:{
    loading:"拼命加载中",
  },
  menuManager:{
    basicManager:"基础管理",
    businessManager:"业务管理",
    cloudManager:"金蝶管理",
  },
  app: {
    personMessage: "个人信息",
    settings: "设置",
    logout: "注销",
    isLogout: "确定要注销吗?",
    tip: "提示",
    sure: "确定",
    cancel: "取消",
  },
  404: {
    404:"404",
    notFindPage: "halaman tidak ditemukan！"
  },
  login: {
    selectCompanyName: "pilih perusahaan",
    inputUserName: "silahkan masukkan nama pengguna",
    inputPassword: "Silahkan masukkan password",
    rememberMe: "ingatkan saya ?",
    login: "masuk",
    loginFor: "masuk",
    errorUserNameOrPassword: "ID atau kata sandi tidak tepat"
  },
  home: {
    home:"home",
    messageForDutyOvertimeRest: "可用加班调休时间",
    hour: "小时",
    messageForDutyAnnualRest: "可用年假调休时间",
    messageForTimeDue: "本月即将到期时间",
    personMessage: "个人信息",
    edit: "修改",
    mobilePhoneEdit: "手机修改申请",
    idCardEdit: "身份证修改申请",
    bankAccountEdit: "银行帐号修改申请",
    officeEdit: "部门变动",
    positionEdit: "岗位变动",
    readerEdit: "上级变动",
    regularEdit: "转正申请",
    leaveEdit: "离职申请",
    companyName: "公司",
    employeeName: "姓名",
    officeName: "部门",
    positionName: "岗位",
    leaderName: "上级",
    regularDate: "转正日期",
    noticeCenter: "通知中心",
    youHave: "您有",
    waitDuty: "待批考勤",
    dutySize: "条待批考勤数据",
    waitAccountTask: "待批任务",
    accountTaskSize: "条待批任务",
    waitReadMessage: "未读消息",
    accountMessageSize: "条新的消息",
    synData: "数据同步",
    selectSynFactoryDate: "选择工厂同步日期",
    synFactory: "同步",
    factoryOrder: "工厂下单",

  },
}
