export default {
  carrierShopList:{
    name: "名称",
    code: "编码",
    sure: "确定",
    save: "保存",
    add: "添加",
    filter: "过滤",
    likeSearch: "模糊搜索",
    createdBy: "创建人",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    edit: "修改",
    delete: "删除",
    loading: "拼命加载中",
  },
  carrierProductList:{
    name: "名称",
    code: "编码",
    sure: "确定",
    save: "保存",
    add: "添加",
    filter: "过滤",
    likeSearch: "模糊搜索",
    createdBy: "创建人",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    edit: "修改",
    delete: "删除",
    loading: "拼命加载中",
  }
}
