export default {
  afterSaleList: {
    afterSaleList: "售后列表",
    bill: "单号",
    badProductIme: "坏机串码",
    badProductName: "坏机货品",
    toAreaProductName: "替换机货品",
    areaDepot: "门店",
    package: "包装",
    memory: "内存",
    toStoreType: "退机类型",
    toStoreDate: "退机日期",
    toStoreDateRemarks: "退机备注",
    fromCompanyDate: "返仓日期",
    toCompanyDate: "返厂日期",
    synFor: "已同步",
    toAreaProductIme: "替换串码",
    packageStatus: "包装情况",
    syn: "同步",
    add: "添加",
    filter: "过滤",
    export: "导出",
    blankOrComma: "空格或逗号隔开",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  afterSaleForm: {
    afterSaleForm: "售后申请",
    alertSearchAfterSaleIme: "请先查询出需要做售后的串码",
    toStoreDate: "退机日期",
    ime: "串码",
    selectDateRange: "选择日期范围",
    badProductName: "坏机型号",
    badProductIme: "坏机串码",
    saleShopName: "核销门店",
    toAreaProductIme: "替换串码",
    areaDepot: "地区",
    packageStatus: "包装",
    toStoreType: "退机类型",
    memory: "内存",
    toStoreTypeRemarks: "退机备注",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  afterSaleImeAllotList: {
    afterSaleImeAllotList: "调拨列表",
    bill: "单号",
    afterSaleBill: "售后单号",
    ime: "串码",
    fromDepot: "调出仓库",
    toDepot: "调后仓库",
    blankOrComma: "空格或逗号隔开",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  afterSaleProductAllotList: {
    afterSaleProductAllotList: "售后盘点",
    bill: "单号",
    afterSaleBill: "售后单号",
    storeName: "仓库",
    fromProductName: "换前货品",
    toProductName: "换后货品",
    toOutCode: "盘盈编号",
    fromOutCode: "盘亏编号",
    blankOrComma: "空格或逗号隔开",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  afterSaleStoreAllotList: {
    afterSaleStoreAllotList: "售后调拨",
    bill: "单号",
    productName: "货品",
    fromStore: "调出仓库",
    toStore: "调后仓库",
    outCode: "财务编号",
    afterSaleBill: "售后单号",
    badProductIme: "坏机串码",
    blankOrComma: "空格或逗号隔开",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  afterSaleAreaEdit: {
    afterSaleAreaEdit: "垫机录入",
    name: "名称",
    fromCompanyDate: "返仓日期",
    badProductName: "坏机型号",
    badProductIme: "坏机串码",
    toAreaProductType: "替换机型号",
    toAreaProductIme: "替换机串码",
    badProductShop: "坏机门店",
    badProductType: "坏机类型",
    adPricesystem: "垫机串码",
    areaDepot: "地区",
    packageStatus: "包装类型",
    toStoreType: "退机类型",
    toStoreDate: "退机日期",
    toCompanyDate: "返厂日期",
    memory: "内存",
    filter: "过滤",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    selectDateRange: "选择日期范围",
  },
  afterSaleEditForm: {
    afterSaleEditForm: "售后申请编辑",
    name: "名称",
    ime: "串码",
    fromCompanyDate: "返仓日期",
    badProductName: "坏机型号",
    badProductIme: "坏机串码",
    saleShopName: "核销门店",
    toAreaProductIme: "替换串码",
    areaDepot: "地区",
    packageStatus: "包装",
    toStoreType: "退机类型",
    memory: "内存",
    fromCompanyProduct: "工厂返回",
    toStoreTypeRemarks: "退机备注",
    alertSearchAfterSaleIme: "请先查询出需要做售后的串码",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  afterSaleFromCompany: {
    afterSaleFromCompany: "好机返库",
    fromCompanyDate: "返仓日期",
    selectDate: "选择日期",
    badProductName: "坏机型号",
    badProductIme: "坏机串码",
    toAreaProductType: "返还型号",
    toCompanyDate: "返厂日期",
    areaDepot: "地区",
    packageStatus: "包装情况",
    toStoreType: "退机类型",
    toStoreDate: "退机日期",
    memory: "内存",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  afterSaleToCompany: {
    afterSaleToCompany: "坏机返厂",
    ime: "串码",
    inputIme: "请输入串码",
    search: "搜索",
    productType: "货品型号",
    qty: "数量",
    badProductName: "坏机型号",
    badProductIme: "坏机串码",
    toAreaProductName: "替换机",
    areaDepot: "地区",
    packageStatus: "包装情况",
    toStoreType: "退机类型",
    memory: "内存",
    remarks: "备注",
    toCompanyDate: "返厂日期",
    selectDate: "选择日期",
    companyRemarks: "返厂备注",
    save: "保存",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    alertDealErrorData: "请处理异常数据后保存",
  },
  bankInForm: {
    bankInForm: "销售收款编辑",
    shopName: "门店",
    type: "类型",
    saleMoney: "销售收款",
    deposit: "定金收款",
    bankName: "银行",
    selectBank: "请选择银行",
    selectType: "请选择类型",
    cash: "现金收款",
    cashIn: "现金收款",
    selectDate: "选择日期",
    amount: "到账金额",
    serialNumber: "流水号",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    prerequisiteAndPositiveNumberMessage: "请输入一个大于0的数值",

  },
  bankInList: {
    bankInList: "销售收款",
    id: "编号",
    shopName: "门店",
    shopClientName:'收款门店',
    realShopName: "收款门店",
    bankName: "银行",
    amount: "金额",
    serialNumber: "流水号",
    billDate: "开单日期",
    inputDate: "到账日期",
    outCode: "财务单号",
    processStatus: "状态",
    batchPass: "批量通过",
    selectProcessStatus: "请选择状态",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    preciseSearch: "精确搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
    noSelectionFound:"没有选中任何记录",
  },
  bankInDetail: {
    bankInDetail: "销售收款编辑",
    shopName: "门店",
    type: "类型",
    bankName: "银行",
    cash: "现金收款",
    inputDate: "到账日期",
    amount: "到账金额",
    serialNumber: "流水号",
    outCode: "外部编号",
    processStatus: "状态",
    createdByName: "创建人",
    synInfo:'金蝶同步',
    synToCloud: "同步到金蝶",
    true: "是",
    false: "否",
    billDate:"开单日期",
    pass: "通过",
    auditRemarks: "审批备注",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    save: "保存",
    remarks:"备注",
    toKingdeeSynList:'查看同步信息',
  },
  demoPhoneForm: {
    demoPhoneForm: "演示用机编辑",
    productType: "可申请型号",
    shopName: "门店",
    productIme: "串码",
    employeeName: "用户",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    selectKeyShow20time: "请输入关键词,显示前20条",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    inputImeLast6:"请输入串码后(>=6)位"
  },
  demoPhoneList: {
    demoPhoneList: "演示用机",
    ime: "串码",
    shopName: "门店",
    demoPhoneType: "演示机类型",
    employeeName: "申请人",
    status: "状态",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
    collect:"汇总",
  },
  demoPhoneTypeOfficeList:{
    demoPhoneTypeOfficeList:"演示机型汇总",
    officeName:"办事处",
    demoPhoneType:"演示机型",
    qty:"数量",
    realQty:"实际数量",
    add:"添加",
    filter:"过滤",
    sure:"确定"
  },
  depotChangeForm: {
    depotChangeForm: "仓库调整编辑",
    depotName: "仓库",
    type: "调整项",
    selectGroup: "请选择分组",
    selectDate:"请选择时间",
    expiryDate: "截止日期",
    oldValue: "修改前",
    newValue: "修改后",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  depotChangeList: {
    depotChangeList: "仓库调整",
    selectGroup: "请选择分类",
    type: "调整项",
    depotName: "仓库",
    expiryDate: "截止日期",
    oldValue: "修改前",
    newValue: "修改后",
    processStatus: "状态",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  depotChangeDetail: {
    depotChangeDetail: "仓库调整详细",
    type: "调整项",
    processStatus: "状态",
    depotName: "仓库",
    expiryDate: "截止日期",
    oldValue: "修改前",
    newValue: "修改后",
    pass: "是否通过",
    remarks: "备注",
    comment: "审批备注",
    save: "保存",
    nodeName: "节点名称",
    auditMan: "审批人",
    auditDate: "审批时间",
    auditRemarks: "审批备注",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  depotDetailList: {
    depotDetailList: "货品库存",
    syn: "同步",
    shopName: "门店",
    productName: "产品名称",
    hasIme: "包含串码",
    outQty: "财务数量",
    qty: "本地数量",
    isSame: "是否相同",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  expressForm: {
    expressForm: "快递管理编辑",
    expressOrderExtendType: "订单类型",
    expressOrderId: "单号",
    expressOrderToDepotId: "门店",
    code: "快递单号",
    weight: "重量",
    qty: "台数",
    tracking: "快递信息",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    nameNotEmptyMessage:"姓名不能为空",
    nameTooLongMessage:"姓名字段过长",
  },
  expressList: {
    expressList: "快递管理",
    code: "快递单号",
    expressCompanyName: "公司名",
    extendType: "单据类型",
    extendBusinessId: "订单编号",
    fromDepotName: "仓库",
    toDepotName: "门店",
    contact: "收件人",
    mobilePhone: "手机",
    address: "地址",
    weight: "重量",
    qty: "台数",
    shouldPay: "应付",
    realPay: "实付",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  expressOrderForm: {
    expressOrderForm: "快递打印编辑",
    fromDepotId: "发货方",
    toDepotId: "收货方",
    expressCompanyId: "快递公司",
    contact: "收件人",
    mobilePhone: "手机",
    address: "地址",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  expressOrderList: {
    expressOrderList: "快递打印",
    confirmBeforeReset: "确认重置吗？",
    selectExtendType: "请选择单据类型",
    true: "是",
    false: "否",
    EMSExportData: "邮政导出",
    address: "地址",
    expressPrintDate: "快递已打印时间",
    outPrintDate: "出库单打印时间",
    shouldGet: "应收运费",
    shouldPay: "应付运费",
    extendType: "订单类型",
    extendBusinessId: "订单号",
    expressCompanyName: "快递公司",
    fromDepotName: "发货方",
    toDepotName: "收货方",
    realPay: "实付运费",
    contact: "收件人",
    mobilePhone: "联系电话",
    expressPrintQty: "打印张数",
    printDate: "打印日期",
    extendForMobilePhone: "手机订单",
    expressCode: "快递单号",
    extendBusinessIdStart: "起始单号",
    expressPrint: "快递单已打印",
    outPrint: "出库单已打印",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出OR邮政导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    preciseSearch:"精确搜索",
    reset:"重置",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  goodsOrderList: {
    goodsOrderList: "货品订货",
    selectNetType: "请选择网络",
    selectStoreType: "请选择仓库类型",
    selectShopType: "请选择发货类型",
    multiEnterOrComma: "多个回车或逗号隔开",
    selectStatus: "请选择状态",
    billDate: "开单日期",
    shipDate: "发货日期",
    outCode: "外部单号",
    createdName: "创建人",
    isUseTicket: "使用电子券",
    shipRemarks: "发货备注",
    number: "编号",
    orderRemarks: "订货备注",
    shopDeposit: "门店定金",
    businessId: "单号",
    status: "状态",
    shop: "门店",
    shipType: "发货类型",
    amount: "总金额",
    shopShouldGet: "开单后应收",
    store: "仓库",
    netType: "网络制式",
    expressCodes: "快递单号",
    expressCode: "快递单号",
    carrierCodes: "商城单号",
    pullStatus: "推送状态",
    operate: "操作",
    storeType: "仓库类型",
    office: "办事处",
    financeCode: "财务单号",
    null: "空值",
    pull: "已推送",
    waitShip: "待发货",
    waitBill: "待开单",
    add: "添加",
    batchAdd: "批量订货",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",

    bill:'开单',
    sign:'签收',
    shipBack:'重发',
    sreturn:'销售退货',
    shipPrint:'快递单',
    print: "出库单",
    ship: "发货",
    lxMallOrder: "天翼购订货",
    mallAdd: "商城订单",
    carrierOrder: "商城相关",
    exportData: "导出",
    goodsOrderImeList: "串码",
    more: "更多",
  },
  goodsOrderForm: {
    goodsOrderForm: "货品订货编辑",
    clientName: "客户",

    shop: "门店",
    selectWord: "请输入关键词,显示前20条",
    parentShop: "总店",
    netType: "网络制式",
    isUseTicket: "使用电子券",
    shipType: "发货类型",
    carrierShop: "商城门店",
    carrierCodes: "商城单号",
    carrierDetails: "商城订单信息",
    shopType: "门店类型",
    priceSystem: "价格体系",
    summary: "汇总信息",
    selectTowKey: "至少2位关键字",
    loading: "拼命加载中",
    productName: "货品名称",
    hasIme: "串码",
    price: "单价",
    qty: "订货数",
    allowOrder: "允许订货",
    areaQty: "办事处已订货",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    lxMallOrder: "天翼购订货",
  },
  goodsOrderDetail: {
    goodsOrderDetail: "货品订货详细",
    businessId: "订单号",
    storeName: "发货仓库",
    shopName: "门店",
    billDate: "开单日期",
    outCode: "外部单号",
    carrierCodes: "商城单号",
    carrierDetails: "商城订单信息",
    remarks: "备注",
    createdLoginName: "创建人",
    createdDate: "创建时间",
    isUseTicket: "使用电子券",
    expressOrder: "快递单号",
    shipType: "发货类型",
    purchaseInfo: "专卖店货品信息",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    billDetail: "开单详情",
    productName: "货品名称",
    qty: "订货数",
    billQty: "实际开单数",
    price: "单价",
    operate: "操作",
    ime: "ime",
    meid: "meid",
    shipDetail: "发货详情",
    productIme: "串码",
    createdByName: "发货人",
    shipDate: "发货日期",
    copy: "复制",
  },
  goodsOrderBill: {
    goodsOrderBill: "货品订货开单",
    costGoodsDeposit:'需扣除定金',
    leftGoodsDeposit:'剩余定金',
    summary:'汇总信息',
    areaBillQty:'办事处已开单数',
    totalProduct:'总货品数',
    totalProductPrice:'总货品金额',
    totalProductDeposit:'扣定金',
    shopShouldGetAfterBill:'开单后应收',

    store: "仓库",
    billDate: "开单日期",
    selectDateRange: "选择日期范围",
    expressCompany: "快递公司",
    synToCloud: "同步到财务",
    goodsOrderRemarks: "订货备注",
    contact: "收件人",
    address: "地址",
    mobilePhone: "手机",
    shouldGet: "门店应收",
    shopRemarks: "门店备注",
    credit: "门店信用额度",
    goodsDeposit: "门店定金",
    shipType: "发货类型",
    carrierCodes: "商城单号",
    carrierDetails: "商城订单信息",
    formatId: "业务单号",
    areaName: "办事处",
    shopName: "门店",
    parentName: "总店",
    shopCredit: "门店信誉度",
    remarks: "需扣除定金",
    title: "剩余定金",
    summery: "汇总信息",
    totalQty: "总开单数",
    totalPrice: "总开单金额",
    goodsOrderRebateRule: "销售折让规则",
    save: "保存",
    filter: "过滤",
    selectTowKey: "至少二位关键字",
    loading: "拼命加载中",
    productName: "货品名称",
    areaQty: "办事处已开单数",
    stock: "库存",
    allowOrder: "允许订货",
    qty: "订货数",
    billQty: "开单数",
    price: "单价",
    hasIme: "包含串码",
    prerequisiteMessage: "必填信息",
    clientName: "客户",
  },
  goodsOrderBatchAdd:{
    shopName: "门店",
    carrierCodes: "商城单号",
    receiveAddress:"收货地址",
    receiver:"收货人",
    tel:"电话",
    remarks:"备注",
    netType:"网络格式",
    type:"型号",
    num:"数量",
    price:"单价",
    shipType:"发货类型",
    save:"保存"
  },
  goodsOrderShipList: {
    goodsOrderShipList: "货品发货",
    selectNetType: "请选择网络",
    selectStoreType: "请选择仓库类型",
    selectShopType: "请选择发货类型",
    multiEnterOrComma: "多个回车或逗号隔开",
    selectStatus: "请选择状态",
    billDate: "开单日期",
    shipDate: "发货日期",
    outCode: "外部单号",
    createdName: "创建人",
    isUseTicket: "使用电子券",
    shipRemarks: "发货备注",
    number: "编号",
    orderRemarks: "订货备注",
    shopDeposit: "门店定金",
    businessId: "单号",
    status: "状态",
    shop: "门店",
    shipType: "发货类型",
    amount: "总金额",
    shopShouldGet: "开单后应收",
    store: "仓库",
    netType: "网络制式",
    expressCodes: "快递单号",
    expressCode: "快递单号",
    carrierCodes: "商城单号",
    pullStatus: "推送状态",
    operate: "操作",
    storeType: "仓库类型",
    office: "办事处",
    financeCode: "财务单号",
    null: "空值",
    pull: "已推送",
    waitShip: "待发货",
    waitBill: "待开单",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",

    bill:'开单',
    sign:'签收',
    shipBack:'重发',
    sreturn:'销售退货',
    shipPrint:'快递单',
    print: "出库单",
    ship: "发货",
    mallOrder:"商城订单",
  },
  goodsOrderShip: {
    goodsOrderShip: "货品订货发货",
    businessId: "订单号",
    storeName: "仓库",
    boxImeStr: "箱号",
    expressCodes: "快递单号",
    shopName: "门店",
    remarks: "备注",
    continueShip: "连续发货",
    imeStr: "串码",
    shipRemarks: "发货备注",
    save: "保存",
    filter: "过滤",
    loading: "拼命加载中",
    productName: "货品名称",
    hasIme: "包含串码",
    finish: "发送完成",
    billQty: "开单数",
    returnQty: "退货数",
    shippedQty: "已发货数",
    leftQty: "待发货数",
    shipQty: "发货数",
  },
  goodsOrderSign: {
    goodsOrderSign: "订单签收",
    businessId: "订单号",
    storeName: "仓库",
    shopName: "门店",
    signIn: "签收",
    loading: "拼命加载中",
    productName: "货品名称",
    shippedQty: "发货数",
    remarks: "备注",
  },
  goodsOrderSreturn: {
    goodsOrderSreturn: "销售退货",
    storeName: "仓库",
    billDate: "开单日期",
    synToCloud: "同步到财务",
    isUseTicket: "使用电子券",
    returnProduct: "退货",
    areaName: "办事处",
    shopName: "门店",
    remarks: "备注",
    credit: "门店信誉度",
    shouldGet: "门店应收",
    loading: "拼命加载中",
    productName: "货品名称",
    qty: "订货数",
    billQty: "开单数",
    returnQty: "退货数",
    hasIme: "串码",
    price: "单价",
  },
  goodsOrderPrint: {},
  imeAllotForm: {
    imeAllotForm: "串码调拨编辑",
    formInvalid:'页面存在错误，请先修正错误',
    search:'搜索',
    reset:'重置',
    notify:'提示',
    imeStr: "串码",
    inputIme: "请输入串码",
    toDepotId: "调拨后",
    name: "产品名称",
    qty: "数量",
    depotName: "仓库",
    productName: "产品型号",
    retailDate:"保卡日期",
    saleFullName: "核销人",
    saleDate: "核销时间",
    saleShopName: "核销门店",
    imeNotBlank: "串码不能为空",
    allotShopNotBlank: "调拨后门店不能为空",
    dealErrorData: "请处理异常数据后保存",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    saleCreatedFullName: "核销人",
    saleCreatedDate: "核销时间",

  },
  carrierOrderForm:{
    orderCode:"订单编号",
    shopDetail:"商城详情",
    prerequisiteMessage:"必填信息",
    save:"保存"
  },
  carrierOrderShip:{
    billCode:"商城单号",
    shipCode:"发货串码"
  },
  imeAllotBatchForm: {
    imeAllotBatchForm: "串码批量调拨编辑",
    formInvalid:'页面存在错误，请先修正错误',
    search:'搜索',
    reset:'重置',
    notify:'提示',
    imeStr: "串码",
    inputIme: "请输入串码",
    toDepotId: "调拨后",
    name: "产品名称",
    qty: "数量",
    depotName: "仓库",
    productName: "产品型号",
    retailDate:"保卡日期",
    saleFullName: "核销人",
    saleDate: "核销时间",
    saleShopName: "核销门店",
    imeNotBlank: "串码不能为空",
    allotShopNotBlank: "调拨后门店不能为空",
    dealErrorData: "请处理异常数据后保存",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    saleCreatedFullName: "核销人",
    saleCreatedDate: "核销时间",

  },
  imeAllotList: {
    imeAllotList: "串码调拨",
    batchPass: "批量通过",
    auditPass:'通过',
    auditNotPass:'不通过',
    fromDepot: "调拨前",
    toDepot: "调拨后",
    ime: "串码",
    productName: "产品名称",
    allotDate: "调拨时间",
    allotEmployee: "调拨人",
    pass: "已通过",
    crossArea: "跨区域调拨",
    status: "状态",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
    confirmBeforeAuditPass: "确认该记录审核通过吗？",
    confirmBeforeAuditNotPass: "确认该记录审核不通过吗？",
    noSelectionFound: "没有选中任何记录",
  },
  priceChangeForm: {
    priceChangeForm: "调价项目编辑",
    name: "名称",
    productTypeId: "货品型号",
    priceChangeDate: "调价日期",
    selectDate: "选择日期",
    uploadEndDate: "上报截止日期",
    productType: "货品型号",
    price3: "三级价格",
    baokaPrice: "保卡价格",
    nameNotBlank: "名称不能为空",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  priceChangeList: {
    priceChangeList: "调价项目",
    name: "名称",
    productType: "货品型号",
    checkPercent: "抽检比例%",
    priceChangeDate: "调价日期",
    uploadEndDate: "上报截止日期",
    status: "状态",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  priceChangeDetail: {
    priceChangeDetail: "调价项目抽检",
    name: "名称",
    productTypeNames: "货品型号",
    priceChangeDate: "调价日期",
    uploadEndDate: "上报截止日期",
    remarks:"备注",
    checkPercent: "抽检比例",
    save: "保存",
    filter: "过滤",
    checkPercentIdNumber: "抽检比例必须为数字值",
  },
  priceChangeImeForm: {
    priceChangeImeForm: "调价串码上传",
    priceChangeId: "调价项目",
    selectPriceChangeId: "请选择调价项目",
    shopName: "门店",
    ime: "串码",
    nameNotBlank: "名称不能为空",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  priceChangeImeList: {
    priceChangeImeList: "调价串码",
    ime: "串码",
    saleDate: "销售日期",
    type: "型号",
    areaName: "办事处",
    officeName: "所属机构",
    shopName: "门店",
    priceChangeName: "调价项目",
    auditDate: "审批时间",
    status: "状态",
    pass: "已通过",
    isCheck: "是否抽检",
    image: "已传照片",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
    upload:"上传",
    uploadPicture:"图片上传"
  },
  priceChangeImeDetail: {
    priceChangeImeDetail: "调价串码编辑",
    priceChangeName: "调价项目",
    type: "型号",
    ime: "串码",
    shopName: "门店",
    imagefile: "附件",
    clickUpload: "点击上传",
    uploadImageSizeFor5000KB: "只能上传图片文件，且不超过500kb",
    pass: "通过",
    auditRemarks: "审批备注",
    save: "保存",
    filter: "过滤",
    remarks: "备注",
  },
  pricesystemChangeForm: {
    pricesystemChangeForm: "货品调价编辑",
    product: "产品",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  pricesystemChangeList: {
    pricesystemChangeList: "货品调价",
    batchPass: "通过",
    productName: "产品",
    pricesystemName: "价格体系",
    oldPrice: "调价前",
    newPrice: "调价后",
    status: "状态",
    pass: "通过",
    noPass:"不通过",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
    noSelectionFound:"未选中任何项",
  },
  productImeList: {
    productImeList: "串码列表",
    batchQuery: "串码批量查询",
    imeOrMeids:'串码(多行)',
    selectInputType: "请选择入库类型",
    ime: "串码",
    ime2: "串码2",
    imeFilter: "请输入串码后六位",
    meid: "meid码",
    retailDate: "工厂保卡日期",
    saleDate: "核销时间",
    uploadDate: "上报时间",
    depotName: "仓库",
    netType: "制式",
    productType: "产品型号",
    inputType: "入库类型",
    createdTime: "工厂创建时间",
    boxIme: "箱号",
    mutilIme: "串码多行",
    retailDateBtw: "保卡注册时间",
    createTimeBtw: "工厂发货时间",
    meids: "MEID(多行)",
    month: "月份",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
    more: "更多",
    sale: "核销",
    saleBack: "核销退回",
    allot: "串码调拨",
    change: "串码调整",
    batchAllot: "串码批量调拨",
    upload: "保卡上报",
    uploadBack: "上报退回",


  },
  productImeCreate: {
    productImeCreate: "串码添加",
    imeOrMeids:'串码(多行)',
    selectInputType: "请选择入库类型",
    ime: "串码",
    ime2: "串码2",
    meid: "meid码",
    retailDate: "工厂保卡日期",
    saleDate: "核销时间",
    uploadDate: "上报时间",
    depotName: "仓库",
    netType: "制式",
    productType: "产品型号",
    inputType: "入库类型",
    createdTime: "工厂创建时间",
    boxIme: "箱号",
    mutilIme: "串码多行",
    retailDateBtw: "保卡注册时间",
    createTimeBtw: "工厂发货时间",
    meids: "MEID(多行)",
    month: "月份",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  productImeChange: {
    productImeChange: "串码调整",
    imeOrMeids:'串码(多行)',
    selectInputType: "请选择入库类型",
    ime: "串码",
    ime2: "串码2",
    meid: "meid码",
    retailDate: "工厂保卡日期",
    saleDate: "核销时间",
    uploadDate: "上报时间",
    depotName: "仓库",
    netType: "制式",
    productType: "产品型号",
    inputType: "入库类型",
    createdTime: "工厂创建时间",
    boxIme: "箱号",
    mutilIme: "串码多行",
    retailDateBtw: "保卡注册时间",
    createTimeBtw: "工厂发货时间",
    meids: "MEID(多行)",
    month: "月份",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  productImeDetail: {
    productImeHistoryId:'编号',
    productImeHistoryType:'类型',
    productImeHistoryFromName:'更新前',
    productImeHistoryToName:'更新后',
    productImeHistoryCreatedByName:'创建人',
    productImeHistoryCreatedDate:'创建时间',
    productImeHistoryRemarks:'备注',
    productName:'产品名称',
    outType:'外部型号',

    productImeDetail: "串码详情",
    selectInputType: "请选择入库类型",
    ime: "串码",
    ime2: "串码2",
    meid: "meid码",
    retailDate: "工厂保卡日期",
    saleDate: "核销时间",
    uploadDate: "上报时间",
    depotName: "仓库",
    netType: "制式",
    productType: "产品型号",
    inputType: "入库类型",
    createdTime: "工厂创建时间",
    boxIme: "箱号",
    mutilIme: "串码多行",
    retailDateBtw: "保卡注册时间",
    createTimeBtw: "工厂发货时间",
    meids: "MEID(多行)",
    month: "月份",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  productImeBatchQuery: {
    productImeBatchQuery: "串码批量查询",
    companyName: "公司",
    export: "导出",
    ime: "串码",
    ime2: "串码2",
    meid:"Meid",
    boxIme: "箱号",
    inputAllIme: "请输入串码、串码2、Meid码、箱号",
    shopId: "核销门店",
    buyer: "用户姓名",
    buyerAge: "用户年龄",
    buyerSex: "性別",
    man: "男",
    women: "女",
    buyerPhone: "电话",
    buyerSchool: "学校",
    buyerGrade: "年级",
    name: "产品名称",
    qty: "数量",
    depotName: "仓库",
    productType: "产品型号",
    baokaDate: "工厂保卡日期",
    shopName: "核销门店",
    createdFullName: "核销人",
    createdDate: "核销时间",
    imeNotBlank: "串码不能为空",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    search:'搜索',
    reset:'重置',
    pleaseCorrectFormDataFirst:'请先修正页面上的错误',
    notify:'提示',
    productImeSaleEmployeeName:'核销人',
    productImeSaleCreatedDate:'核销时间',
    productImeUploadEmployeeName:'保卡上报员工',
    productImeUploadMonth:'保卡上报月份',
    productImeUploadCreatedDate:'保卡上报时间',
  },
  productImeSaleForm: {
    productImeSaleForm: "串码核销编辑",
    ime: "串码",
    formInvalid: "表单存在错误，请先修正",
    inputIme: "请输入串码",
    shopId: "核销门店",
    buyer: "用户姓名",
    buyerAge: "用户年龄",
    buyerSex: "性別",
    man: "男",
    women: "女",
    buyerPhone: "电话",
    buyerSchool: "学校",
    buyerGrade: "年级",
    name: "产品名称",
    qty: "数量",
    depotName: "仓库",
    productType: "产品型号",
    baokaDate: "工厂保卡日期",
    shopName: "核销门店",
    createdFullName: "核销人",
    createdDate: "核销时间",
    imeNotBlank: "串码不能为空",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    prerequisiteAndNumberMessage: "请输入一个合法的数值",
    inputLegalValue: "请输入合法的数值",
    search:'搜索',
    reset:'重置',
    pleaseCorrectFormDataFirst:'请先修正页面上的错误',
    notify:'提示',
    productImeSaleEmployeeName:'核销人',
    productImeSaleCreatedDate:'核销时间',
    productImeUploadEmployeeName:'保卡上报员工',
    productImeUploadCreatedDate:'保卡上报时间',
    pleaseSelectSaleShop:'请选择核销门店',
    alreadySaleShopName:'已核销门店',
    saleShopName:'核销门店',
  },

  productImeSaleBackForm: {
    productImeSaleForm: "串码核销编辑",
    ime: "串码",
    inputIme: "请输入串码",
    name: "产品名称",
    qty: "数量",
    formInvalid: "表单存在错误，请先修正",
    depotName: "仓库",
    productType: "产品型号",
    baokaDate: "工厂保卡日期",
    shopName: "核销门店",
    createdFullName: "核销人",
    createdDate: "核销时间",
    imeNotBlank: "串码不能为空",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    search:'搜索',
    reset:'重置',
    pleaseCorrectFormDataFirst:'请先修正页面上的错误',
    notify:'提示',
    productImeSaleEmployeeName:'核销人',
    productImeSaleCreatedDate:'核销时间',
    productImeUploadEmployeeName:'保卡上报员工',
    productImeUploadCreatedDate:'保卡上报时间',
    info:'只能退回自己核销的串码，只能退回未上报的串码',

  },
  productImeSaleList: {
    productImeSaleList: "串码核销",
    saleShopName: "核销门店",
    sale:'核销',
    saleBack:'退回',
    inputImeTail:'请输入串码后六位',
    ime: "串码",
    saleDate: "核销时间",
    productName: "产品名称",
    employeeName: "核销人",
    isBack: "是否退回",
    name: "名称",
    shopName: "门店",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  productImeUploadForm: {
    productImeUploadForm: "串码上报编辑",
    ime: "串码",
    formInvalid: "表单存在错误，请先修正",
    notify: "提示",
    inputIme: "请输入串码",
    month: "月份",
    selectDate: "选择日期",
    shopId: "门店",
    saleEmployee: "促销员",
    name: "产品名称",
    qty: "数量",
    depotName: "仓库",
    productName: "产品型号",
    retailDate: "保卡日期",
    saleShopName: "核销门店",
    saleCreatedFullName: "核销人",
    saleCreatedDate: "核销时间",
    uploadShopName: "上报门店",
    updateDate: "上报时间",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    reset:'重置',
    search:'搜索',
    pleaseInputImes:'请输入串码',
    productImeUploadStatus:'上报状态',
  },
  productImeUploadBackForm: {
    productImeUploadBackForm: "串码上报退回编辑",
    instruction: "只有在自己管辖门店内上报并且没有通过的才可以核销退回",
    ime: "串码",
    uploadBack:'上报退回',
    formInvalid: "表单存在错误，请先修正",
    notify: "提示",
    inputIme: "请输入串码",
    month: "月份",
    selectDate: "选择日期",
    shopId: "门店",
    saleEmployee: "促销员",
    name: "产品名称",
    qty: "数量",
    depotName: "仓库",
    productName: "产品型号",
    retailDate: "保卡日期",
    saleShopName: "核销门店",
    saleCreatedFullName: "核销人",
    saleCreatedDate: "核销时间",
    uploadShopName: "上报门店",
    updateDate: "上报时间",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    reset:'重置',
    search:'搜索',
    pleaseInputImes:'请输入串码',
    productImeUploadStatus:'上报状态',
  },
  productImeBatchUploadForm: {
    productImeBatchUploadForm: "串码批量上报编辑",
    confirmBatchUpload: "确认批量上报吗？",
    ime: "串码",
    formInvalid: "表单存在错误，请先修正",
    notify: "提示",
    areaId: "办事处",
    month: "月份",
    selectDate: "选择日期",
    shopId: "门店",
    saleEmployee: "促销员",
    name: "产品名称",
    qty: "数量",
    depotName: "仓库",
    productName: "产品型号",
    retailDate: "保卡日期",
    saleShopName: "核销门店",
    saleCreatedFullName: "核销人",
    saleCreatedDate: "核销时间",
    uploadShopName: "上报门店",
    updateDate: "上报时间",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    reset:'重置',
    search:'搜索',
    pleaseInputImes:'请输入串码',
    productImeUploadStatus:'上报状态',
  },
  productImeUploadList: {
    upload:"上报",
    batchUpload:"批量上报",
    back:"退回",
    productImeUploadList: "串码上报",
    imeOrMeidsMultiLine:'可输入多行',
    imeOrMeids:'ime或meid(多行)',
    noSelectionFound:'没有选中任何记录',
    batchPass: "批量通过",
    month: "月份",
    updateShopName: "上报门店",
    ime: "串码",
    updateDate: "上报时间",
    employeeName: "上报人",
    status: "上报状态",
    pass: "已通过",
    officeId: "部门",
    shopName: "门店",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  productMonthPriceForm: {
    productMonthPriceForm: "每月价格编辑",
    month: "月份",
    selectDate: "选择日期",
    totalName: "统计名称",
    baokaPrice: "保卡价格",
    price3: "三级价格",
    price2: "零售价格",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    searchProductTypeName: "搜索统计名称",
    formInvalid: "表单存在错误，请先修正",
    notify: "提示",

  },
  productMonthPriceList: {
    productMonthPriceList: "每月价格",
    id: "编码",
    month: "月份",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  reportScoreAreaList: {
    reportScoreAreaList: "办事处排名",
    reportScoreOfficeRank: "考核区域排名",
    scoreDate: "日期",
    officeName: "办事处",
    score:"当日打分",
    monthScore: "月累计打分",
    dateRank: "当日排名",
    monthRank: "月累计排名",
    saleQty: "当日销量",
    monthSaleQty: "当月销量",
    recentMonthSaleQty: "最近月销量",
    point:"点位",
    monthSaleMoney: "月累计销售额",
    pointMonthSaleMoney: "月累计单点销售额",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  reportScoreForm: {
    reportScoreForm: "每日打分编辑",
    scoreDate: "日期",
    selectScoreDate: "选择打分日期",
    companyScore: "工厂打分",
    companyMonthScore: "工厂月累计打分",
    cardQty: "当日电子保卡数",
    monthCardQty: "月累计电子保卡数",
    rank: "月累计排名",
    productNames: "当前打分型号为",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
  },
  reportScoreList: {
    reportScoreList: "每日打分",
    scoreDate: "日期",
    companyScore: "综合日分",
    companyMonthScore: "综合月分",
    score: "日分",
    monthScore: "月分",
    cardQty: "日保卡",
    monthCardQty: "月保卡",
    rank: "月排名",
    saleQty: "日销",
    monthSaleQty: "月销",
    recentMonthSaleQty: "最近月销",
    saleMoney: "日额",
    monthSaleMoney: "月额",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  reportScoreOfficeList: {
    reportScoreOfficeList: "每日排名",
    officeRank: "办事处排名",
    scoreDate: "日期",
    officeName: "考核区域",
    areaName: "办事处",
    score: "当日打分",
    monthScore: "月累计打分",
    dateRank: "当日排名",
    monthRank: "月累计排名",
    saleQty: "当日销量",
    monthSaleQty: "当月销量",
    recentMonthSaleQty: "最近月销量",
    point: "点位",
    monthSaleMoney: "月累计销售额",
    pointMonthSaleMoney: "月累计单点销售额",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  storeAllotForm: {
    storeAllotForm: "大库调拨编辑",
    allotType: "调拨方式",
    fromStore: "调拨前",
    toStore: "调拨后",
    shipType: "发货类型",
    expressCompany: "快递公司",
    syn: "同步到财务",
    productName: "货品",
    inputKeyOf100Item: "请输入关键字，只显示前100条记录",
    cloudQty: "财务库存",
    billQty: "调拨数",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    remarks: "备注",
    sure: "确定",
    delete: "删除",
    save: "保存",
    filter: "过滤",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "请输入合法的数值",
    yes:"是",
    no:"否",
    selectTowKey:"输入关键字",
  },
  storeAllotList: {
    storeAllotList: "大库调拨",
    ship: "发货",
    businessId: "单据编号",
    fromStore: "调拨前",
    toStore: "调拨后",
    outCode: "外部编号",
    status: "状态",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
    print:"出库单",
    shipPrint:"快递单",
  },
  storeAllotDetail: {
    storeAllotDetail: "大库调拨详细",
    businessId: "单据编号",
    fromStore: "调拨前",
    toStore: "调拨后",
    outCode: "财务单号",
    expressOrder: "快递单号",
    productName: "货品名称",
    billQty: "开单数",
    shippedQty: "已发货数",
    createdBy: "创建人",
    createdDate: "创建时间",
    remarks: "备注",
    productIme:"串码",
    productMeid:"Meid",
    sendByName:"发货人",
    sendDate:"发货时间",
    loading:"拼命加载中",
  },
  storeAllotShip: {
    storeAllotShip: "大库调拨发货",
    save: "保存",
    loading:"拼命加载中",
    businessId: "调拨号",
    fromStore: "调拨前",
    toStore: "调拨后",
    boxImeStr: "箱号",
    imeStr: "串码",
    expressCodes: "快递单号",
    productName: "货品名称",
    hasIme: "包含串码",
    remarks: "发货备注",
    billQty: "开单数",
    shippedQty: "已发货数",
    leftQty: "待发货数",
    shipQty: "发货数",
  },
  dataReportList: {
    dataReportList: "合计报表",
    name: "名称",
    saleQtyForBaoka: "保卡销量",
    baokaSalePercentage: "保卡销量占比(%)",
    saleStockForBaoka: "保卡库存",
    baokaStockPercentage: "保卡库存占比(%)",
    saleQtyForSale: "核销销量",
    salePercentage: "核销销量占比(%)",
    saleStockForSale: "核销库存",
    saleStockPercentage: "核销库存占比(%)",
    black: "返回",
    total: "合计",
    dateRange: "日期范围",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
  depotAccountDetail: {
    depotAccountDetail: "应收报表详细",
    loading: "拼命加载中",
    billType: "业务类型",
    billNo: "单据号",
    date: "记账日期",
    materialName: "名称",
    qty: "数量",
    price: "单价",
    amount: "金额",
    payableAmount: "应收",
    actualPayAmount: "实收",
    endAmount: "期末",
    note: "备注",
    receiveAmount: "预收",
    shouldGet: "应收",
    endShouldGet: "期末",
    remarks: "备注",

  },
  depotAccountList: {
    depotAccountList: "应收报表",
    exportDetail:"导出(有明细)",
    exportConfirmation:"确认书导出",
    exportAllDepots:"导出(所有门店)",
    officeName: "机构",
    areaName: "办事处",
    name: "名称",
    qcys: "期初应收",
    qmys: "期末应收",
    xxbzj: "形象保证金",
    scbzj: "市场保证金",
    ysjyj: "演示机押金",
    dateRange: "日期",
    isSpecialityStore: "是否体验店",
    add: "添加",
    filter: "过滤",
    export: "导出",
    filterOrExport: "过滤OR导出",
    selectDateRange: "选择日期范围",
    inputKey: "请输入关键字",
    inputWord: "请输入关键词",
    likeSearch: "模糊搜索",
    sure: "确定",
    loading: "拼命加载中",
    unicode: "编码",
    createdBy: "创建人",
    createdDate: "创建时间",
    lastModifiedBy: "最后修改人",
    lastModifiedDate: "最后修改时间",
    enabled: "有效",
    locked: "锁定",
    remarks: "备注",
    operation: "操作",
    detail: "详细",
    edit: "修改",
    delete: "删除",
    audit: "审核",
  },
}
