export default {
  carrierShopList:{
    name: "nama",
    code: "kode",
    sure: "yakin",
    save: "simpan",
    add: "tambah",
    filter: "saring",
    likeSearch: "PENCARIAN",
    createdBy: "dibuat oleh",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    edit: "ubah",
    delete: "hapus",
    loading: "memuat",
  },
  carrierProductList:{
    name: "nama",
    code: "kode",
    sure: "yakin",
    save: "simpan",
    add: "tambah",
    filter: "saring",
    likeSearch: "PENCARIAN",
    createdBy: "dibuat oleh",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    edit: "ubah",
    delete: "hapus",
    loading: "memuat",
  }
}
