export default {
  carrierShopList:{
    name: "nama",
    code: "kode",
    sure: "yakin",
    save: "simpan",
    add: "tambah",
    filter: "saring",
    likeSearch: "PENCARIAN",
    createdBy: "dibuat oleh",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    edit: "ubah",
    delete: "hapus",
    loading: "memuat",
  },
  carrierShopForm:{
    name: "nama",
    code: "kode",
    type: "jenis",
    remarks: "keterangan / komen",
    save: "simpan",
    selectGroup:"pilih grup",
    prerequisiteMessage:"Informasi yang diperlukan"
  },
  carrierProductList:{
    name: "nama",
    code: "kode",
    sure: "yakin",
    save: "simpan",
    add: "tambah",
    filter: "saring",
    likeSearch: "PENCARIAN",
    createdBy: "dibuat oleh",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    edit: "ubah",
    delete: "hapus",
    loading: "memuat",
  },
  carrierProductForm:{
    name: "nama",
    productName: "nama produk",
    mallProductTypeName:"商城机型名称",
    remarks: "keterangan / komen",
    save: "simpan",
    prerequisiteMessage:"Informasi yang diperlukan"
  },
}
