export default {
  afterSaleAreaEdit: {
    afterSaleAreaEdit: "setelah penjualan",
    name: "nama",
    fromCompanyDate: "tanggal",
    badProductName: "nama produk rusak",
    badProductIme: "nama produk rusak",
    toAreaProductType: "tipe area produk",
    toAreaProductIme: "strinf=g kode area produk",
    badProductShop: "tokko barang rusak",
    badProductType: "tipe barang rusak",
    adPricesystem: "sistem string kode",
    areaDepot: "area",
    packageStatus: "status paket",
    toStoreType: "tipe toko",
    toStoreDate: "退机日期",
    toCompanyDate: "返厂日期",
    memory: "ingatan",
    filter: "sarimg",
    inputKey: "masukkan kata kunci",
    inputWord: "masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan",
    sure: "yakin",
    save: "simpan",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "masukkan angka yanng valid",
    selectDateRange: "pilih rentang tanggal"
  },
  afterSaleEditForm: {
    afterSaleEditForm: "formulir service center",
    name: "nama",
    ime: "串码",
    fromCompanyDate: "tanggal",
    badProductName: "nama barang rusak",
    badProductIme: "kode barang rusak",
    saleShopName: "nama toko",
    toAreaProductIme: "strind kode produk area",
    areaDepot: "area",
    packageStatus: "statua paket",
    toStoreType: "jenis",
    memory: "ingatan",
    fromCompanyProduct: "produk",
    toStoreTypeRemarks: "keterangan",
    alertSearchAfterSaleIme: "请先查询出需要做售后的串码",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  afterSaleForm: {
    afterSaleForm: "formulir service center",
    alertSearchAfterSaleIme: "pilih imei setelah penjualan",
    toStoreDate: "tanggal",
    ime: "串码",
    selectDateRange: "pilih rentang tanggal",
    badProductName: "nama barang rusak",
    badProductIme: "kode barang rusak",
    saleShopName: "nama toko",
    toAreaProductIme: "string kode produk area",
    areaDepot: "area",
    packageStatus: "status paket",
    toStoreType: "jenis",
    memory: "ingatan",
    toStoreTypeRemarks: "keterangan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  afterSaleFromCompany: {
    afterSaleFromCompany: "gudang barang bagus",
    fromCompanyDate: "tanggal",
    selectDate: "pilih tanggal",
    badProductName: "nama barang rusak",
    badProductIme: "kode barang rusak",
    toAreaProductType: "jenis",
    toCompanyDate: "tanggal",
    areaDepot: "area",
    packageStatus: "statuis paket",
    toStoreType: "jenis",
    toStoreDate: "tanggal",
    memory: "ingatan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  afterSaleImeAllotList: {
    afterSaleImeAllotList: "daftar alokasi",
    bill: "nomor nota",
    afterSaleBill: "kode service center",
    ime: "string kode",
    fromDepot: "调出仓库",
    toDepot: "调后仓库",
    blankOrComma: "kosong atau koma",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  afterSaleList: {
    afterSaleList: "tabel service center",
    bill: "nomor nota",
    badProductIme: "nama barang rusak",
    badProductName: "kode barang rusak",
    toAreaProductName: "nama produk",
    areaDepot: "nama toko",
    package: "paket",
    memory: "ingatan",
    toStoreType: "jenis",
    toStoreDate: "tanggal",
    toStoreDateRemarks: "keterangan",
    fromCompanyDate: "tanggal",
    toCompanyDate: "tanggal",
    synFor: "已同步",
    toAreaProductIme: "string kode",
    packageStatus: "status paket",
    syn: "同步",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    blankOrComma: "空格或逗号隔开",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  afterSaleProductAllotList: {
    afterSaleProductAllotList: "service center",
    bill: "nomor nota",
    afterSaleBill: "nomor service center",
    storeName: "gudang",
    fromProductName: "nama produk",
    toProductName: "nama produk",
    toOutCode: "kode masuk",
    fromOutCode: "kode keluar",
    blankOrComma: "kosong atau koma",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  afterSaleStoreAllotList: {
    afterSaleStoreAllotList: "service center",
    bill: "nomor nota",
    productName: "nama produk",
    fromStore: "gudang keluar",
    toStore: "gudang masuk",
    outCode: "kode keluar",
    afterSaleBill: "nomor service center",
    badProductIme: "string kode barang rusak",
    blankOrComma: "kosong atau koma",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  afterSaleToCompany: {
    afterSaleToCompany: "坏机返厂",
    ime: "string kode",
    inputIme: "masukkan string kode",
    search: "pencarian",
    productType: "tipe produk",
    qty: "jumlah",
    badProductName: "kode barang rusak",
    badProductIme: "string kode barang rusak",
    toAreaProductName: "area",
    areaDepot: "area",
    packageStatus: "status paket",
    toStoreType: "jenis",
    memory: "ingatan",
    remarks: "leterangan",
    toCompanyDate: "tanggal",
    selectDate: "pilih tanggal",
    companyRemarks: "keterangan",
    save: "simpan",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "masukkan angka yang valid",
    alertDealErrorData: "masukkan angka yang valid"
  },
  bankInDetail: {
    bankInDetail: "kredit penjualan",
    shopName: "nama toko",
    type: "jenis",
    bankName: "bank",
    cash: "uang tunai",
    inputDate: "到账日期",
    amount: "jumlah uang",
    serialNumber: "nominal",
    outCode: "外部编号",
    processStatus: "status",
    createdByName: "创建人",
    synInfo:'金蝶同步',
    synToCloud: "sinkronisasi",
    true: "benar",
    false: "salah",
    pass: "konfirmasi",
    auditRemarks: "keterangan pemeriksaan",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "masukkan angka yang valid",
    save: "simpan",
    remarks: "备注",
  },
  bankInForm: {
    bankInForm: "tambah kredit penjualan",
    shopName: "门店",
    type: "jenis",
    saleMoney: "kredit penjualan",
    deposit: "deposit",
    bankName: "bank",
    selectBank: "pilih bank",
    selectType: "请选择类型",
    cash: "uang tunai",
    cashIn: "uang tunai",
    selectDate: "pilih tanggal",
    amount: "jumlah",
    serialNumber: "nominal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid,"
  },
  bankInList: {
    bankInList: "kredit penjualan",
    id: "ID",
    shopName: "nama toko",
    shopClientName:'收款门店',
    realShopName: "toko pelanggan",
    bankName: "bank",
    amount: "jumlah",
    serialNumber: "nominal",
    billDate: "tanggal nota",
    inputDate: "tanggal input",
    outCode: "nomor keuangan",
    processStatus: "status",
    batchPass: "saring",
    selectProcessStatus: "pilih status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    preciseSearch: "精确搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dataReportList: {
    dataReportList: "daftar data",
    name: "nama",
    saleQtyForBaoka: "Penjualan kartu jaminan",
    baokaSalePercentage: "persentase penjualan",
    saleStockForBaoka: "persediaan",
    baokaStockPercentage: "persentase persediaan",
    saleQtyForSale: "verifikasi penjualan",
    salePercentage: "persentase verifikasi penjualan",
    saleStockForSale: "verifikasi persediaan",
    saleStockPercentage: "persentase verifikasi persediaan",
    black: "kembali",
    total: "合计",
    dateRange: "日期范围",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  demoPhoneForm: {
    demoPhoneForm: "demo memakai mesin",
    productType: "nomor demo",
    shopName: "nama toko",
    productIme: "string kode",
    employeeName: "nama karyawan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    selectKeyShow20time: "请输入关键词,显示前20条",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  demoPhoneList: {
    demoPhoneList: "demo mesin",
    ime: "string kode",
    shopName: "nama toko",
    demoPhoneType: "demo mesin",
    employeeName: "nama karyawan",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  depotAccountDetail: {
    depotAccountDetail: "Akun Laporan Detail",
    loading: "memuat",
    billType: "jenis nota",
    billNo: "nomor nota",
    date: "tanggal",
    materialName: "nama",
    quantity: "jumlah",
    price: "harga",
    amount: "jumlah",
    payableAmount: "jumlah pwmbayaran",
    actualPayAmount: "pembayaran pokok",
    endAmount: "total pembayaran",
    note: "keterangan"
  },
  depotAccountList: {
    depotAccountList: "akun laporan",
    exportData: "ekspor data",
    exportDataDetail: "ekspor perincian",
    officeName: "nama kantor",
    areaName: "area",
    name: "nama",
    qcys: "piutang",
    qmys: "utang",
    xxbzj: "margin",
    scbzj: "obligasi",
    ysjyj: "演示机押金",
    dateRange: "tanggal",
    isSpecialityStore: "是否体验店",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  depotChangeDetail: {
    depotChangeDetail: "Rincian penyesuaian gudang",
    type: "tipe",
    processStatus: "status",
    depotName: "gudang",
    expiryDate: "tangal jatuh tempo",
    oldLabel: "sebelum modifikasi",
    newValue: "sesudah modifikasi",
    pass: "apakah sudah dikonfitmasi",
    remarks: "keterangan",
    comment: "komen",
    save: "simpan",
    nodeName: "nama",
    auditMan: "orang pemeriksaan",
    auditDate: "tanggal pemeriksaan",
    auditRemarks: "keterangan pemeriksaan",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "masukkan angka yang vallid"
  },
  depotChangeForm: {
    depotChangeForm: "formulir gudang",
    depotName: "gudang",
    type: "jenis",
    selectGroup: "pilih grup",
    expiryDate: "tanggal jatuh tempo",
    oldValue: "sebelum dimodifikasi",
    newValue: "sesudah dimodifikasi",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  depotChangeList: {
    depotChangeList: "仓库调整",
    depotName: "gudang",
    type: "jenis",
    selectGroup: "pilih grup",
    expiryDate: "tanggal jatuh tempo",
    oldValue: "sebelum dimodifikasi",
    newValue: "sesudah dimodifikasi",
    processStatus: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  depotDetailList: {
    depotDetailList: "persediaan barang",
    syn: "sinkronisasi",
    shopName: "toko",
    productName: "nama barang",
    hasIme: "strink kode",
    outQty: "kuantitas",
    qty: "jumlah",
    isSame: "apakah sama",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  expressForm: {
    expressForm: "Ekspres managing editor",
    expressOrderExtendType: "jenis order",
    expressOrderId: "kode nota",
    expressOrderToDepotId: "toko",
    code: "kode resi",
    weight: "berat",
    qty: "kuantitas",
    tracking: "paket pengiriman",
    inputKey: "masukkan kata kunci",
    inputWord: "masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "必填信息",
    nameNotEmptyMessage:"姓名不能为空",
    nameTooLongMessage:"姓名字段过长",

  },
  expressList: {
    expressList: "manajemen pengiriman",
    code: "快递单号",
    expressCompanyName: "nama perusahaan",
    extendType: "Tipe dokumen",
    extendBusinessId: "kode dokumen",
    fromDepotName: "gudang",
    toDepotName: "toko",
    contact: "kontak",
    mobilePhone: "telepon",
    address: "alaamt",
    weight: "berat",
    qty: "kuantitas",
    shouldPay: "应付",
    realPay: "实付",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  expressOrderForm: {
    expressOrderForm: "Mengungkapkan Percetakan Editing",
    fromDepotId: "kapal",
    toDepotId: "kapal",
    expressCompanyId: "perusahaan jasa pengiriman",
    contact: "kontak",
    mobilePhone: "telepon",
    address: "alamat",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  expressOrderList: {
    expressOrderList: "daftar jasa pengiriman",
    selectExtendType: "pilih perpanjangan waktu",
    true: "benar",
    false: "salah",
    EMSExportData: "ekspor data",
    address: "alamat",
    expressPrintDate: "tanggal percetakan pengiriman",
    outPrintDate: "tanggal cetak",
    shouldGet: "piutang pengiriman",
    shouldPay: "utang pengiriman",
    extendType: "jenis order",
    extendBusinessId: "kode order",
    expressCompanyName: "perusahaan jasa pengiriman",
    fromDepotName: "发货方",
    toDepotName: "penerima",
    realPay: "pembayaran",
    contact: "kontak",
    mobilePhone: "nomor telepon",
    expressPrintQty: "jumlah cetak",
    printDate: "tanggal cetak",
    extendForMobilePhone: "手机订单",
    expressCode: "kode resi",
    extendBusinessIdStart: "起始单号",
    expressPrint: "kode cetak resi",
    outPrint: "cetak",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    preciseSearch:"精确搜索",
    reset:"重置",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  goodsOrderBill: {
    goodsOrderBill: "pengiriman barang",
    store: "gudang",
    billDate: "tanggal",
    selectDateRange: "pilih tanggal",
    expressCompany: "perusahaan jasa pengiriman",
    synToCloud: "sinkronisasi",
    goodsOrderRemarks: "keterangan pemesanan",
    contact: "kontak",
    address: "alamat",
    mobilePhone: "telepon",
    shouldGet: "toko dapat",
    shopRemarks: "keterangan toko",
    credit: "pendapatan toko",
    goodsDeposit: "deposit toko",
    shipType: "jenis pengiriman",
    carrierCodes: "kode karir",
    carrierDetails: "perincian",
    formatId: "Nomor bisnis tunggal",
    areaName: "area",
    shopName: "toko",
    parentName: "toko",
    shopCredit: "pendapatan toko",
    remarks: "keterangan",
    title: "judul",
    summery: "ringkasan",
    totalQty: "total kuantitas",
    totalPrice: "total harga",
    goodsOrderRebateRule: "Aturan diskon penjualan",
    save: "simpan",
    filter: "saring",
    selectTowKey: "setidaknya 2kunci",
    loading: "memuat",
    productName: "nama produk",
    areaQty: "area",
    stock: "gudang",
    allowBill: "memungkikan pemesanan",
    qty: "kuantitas",
    billQty: "jumlah nota",
    price: "harga",
    hasIme: "string kode"
  },
  goodsOrderDetail: {
    goodsOrderDetail: "货品订货详细",
    businessId: "kode nota",
    storeName: "gudang pengiriman",
    shopName: "toko",
    billDate: "tanggal buka nota",
    outCode: "kode keluar",
    carrierCodes: "kode karir",
    carrierDetails: "perincian",
    remarks: "keterangan",
    createdLoginName: "dibuat",
    createdDate: "dibuat pada tanggal",
    isUseTicket: "Kupon elektronik",
    expressOrder: "kode resi",
    shipType: "jenis pengiriman",
    purchaseInfo: "Informasi toko Barang",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "masukkan angka yang valid",
    billDetail: "开单详情",
    productName: "货品名称",
    qty: "订货数",
    billQty: "实际开单数",
    price: "单价",
    operate: "操作",
    ime: "ime",
    meid: "meid",
    shipDetail: "发货详情",
    productIme: "串码",
    createdByName: "发货人",
    shipDate: "发货日期",
    copy: "复制",
  },
  goodsOrderForm: {
    goodsOrderForm: "pengiriman barang",
    shop: "toko",
    selectWord: "Masukkan kata kunci ditampilkan sebelum 20",
    parentShop: "toko",
    netType: "standar jaringan",
    isUseTicket: "Kupon elektronik",
    shipType: "jenis pengiriman",
    carrierShop: "toko karir",
    carrierCodes: "kode karir",
    carrierDetails: "perincian",
    shopType: "jenis toko",
    priceSystem: "sistem harga",
    summary: "ringkasan",
    selectTowKey: "Setidaknya dua kunci",
    loading: "memuat",
    productName: "nama produk",
    hasIme: "string kode",
    price: "harga",
    qty: "kuantitas",
    allowOrderAndBill: "Untuk memungkinkan Corporation",
    areaQty: "Kantor telah memerintahkan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  goodsOrderList: {
    goodsOrderList: "pengiriman barang",
    selectNetType: "Pilih Network",
    selectStoreType: "Pilih jenis gudang",
    selectShopType: "Silakan pilih jenis pengiriman",
    multiEnterOrComma: "Masukkan koma atau pluralitas spasi terpisah",
    selectStatus: "pilih status",
    billDate: "tanggal buka nota",
    shipDate: "tanggal pengiriman",
    outCode: "kode keluar",
    createdName: "dibuat",
    isUseTicket: "Kupon elektronik",
    shipRemarks: "keterangan pengiriman",
    number: "kode",
    orderRemarks: "keterangan pemesanan",
    shopDeposit: "deposit toko",
    businessId: "kode",
    status: "status",
    shop: "toko",
    shipType: "jenis pengiriman",
    amount: "jumlah",
    shopShouldGet: "Setelah akun penagihan",
    store: "gudang",
    netType: "standar jaringan",
    expressCodes: "kode resi",
    expressCode: "kode resi",
    carrierCodes: "kode karir",
    pullStatus: "status",
    operate: "operasi",
    storeType: "jenis gudang",
    office: "kantor",
    financeCode: "kode keuangan,",
    null: "nilai",
    pull: "terdorong",
    waitShip: "menunggu pengiriman",
    waitBill: "menunggu buka nota",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah",


    bill:'开单',
    sign:'签收',
    shipBack:'重发',
    sreturn:'销售退货',
    shipPrint:'快递单',
    print: "出库单",
    ship: "发货",
  },
  goodsOrderPrint: {},
  goodsOrderShip: {
    goodsOrderShip: "pengiriman barnag",
    businessId: "nomor order",
    storeName: "gudang",
    boxImeStr: "nomor kode pos",
    expressCodes: "kode resi",
    shopName: "toko",
    remarks: "keterangan",
    redictView: "pengiriman",
    imeStr: "string kdoe",
    shipRemarks: "keterangan pengiriman",
    save: "simpan",
    filter: "saring",
    loading: "memuat",
    productName: "nama produk",
    hasIme: "string kode",
    billQty: "jumlah nota",
    returnQty: "jumlah returan",
    shippedQty: "jumlah pengiriman",
    waitShipQty: "menunggu pengiriman",
    shipQty: "jumlah pengiriman barang"
  },
  goodsOrderSign: {
    goodsOrderSign: "订单签收",
    businessId: "订单号",
    storeName: "仓库",
    shopName: "门店",
    signIn: "签收",
    loading: "拼命加载中",
    productName: "货品名称",
    shippedQty: "发货数",
    remarks: "备注",
  },
  goodsOrderSreturn: {
    goodsOrderSreturn: "销售退货",
    storeName: "仓库",
    billDate: "tanggal buka nota",
    synToCloud: "同步到财务",
    isUseTicket: "Kupon elektronik",
    returnProduct: "retur barang",
    areaName: "area",
    shopName: "toko",
    remarks: "keterangan / komen",
    credit: "toko",
    shouldGet: "toko terima",
    loading: "memuat",
    productName: "nama produk",
    qty: "kuantitas",
    billQty: "jumlah nota",
    returnQty: "jumlah returan",
    hasIme: "string kode",
    price: "harga"
  },
  imeAllotForm: {
    imeAllotForm: "Alokasi mengedit string kode",
    imeStr: "string kdoe",
    inputIme: "masukkan string kode",
    toDepotId: "setelah transfer",
    name: "nama produk",
    qty: "kuantitas",
    depotName: "gudang",
    productName: "kode produk",
    retailDate: "tanggal",
    saleFullName: "verifikasi karyawan",
    saleDate: "verifikasi tanggal",
    saleShopName: "verifikasi toko",
    imeNotBlank: "string kode tidak bole kosong",
    allotShopNotBlank: "Setelah alokasi toko tidak boleh kosong",
    dealErrorData: "Harap menyimpan data pengecualian diproses",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  imeAllotList: {
    imeAllotList: "alokasi string kode",
    batchPass: "konfirmasi",
    fromDepot: "sebelum transfer",
    toDepot: "sesudah transfer",
    ime: "string kdoe",
    productName: "nama produk",
    allotDate: "sebelum transfer",
    allotEmployee: "Pemindahan orang",
    pass: "konfirmasi",
    crossArea: "area",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  priceChangeDetail: {
    priceChangeDetail: "Proyek sampel Harga",
    name: "nama",
    productTypeNames: "kode produk",
    priceChangeDate: "alokasi tanggal",
    uploadEndDate: "unggah tanggal selesai",
    remarks: "keterangan / komen",
    checkPercent: "rasio Sampling",
    save: "simpan",
    filter: "saring",
    checkPercentIdNumber: "Sampling rasio harus menjadi nilai numerik"
  },
  priceChangeForm: {
    priceChangeForm: "Harga mengedit proyek",
    name: "nama",
    productTypeId: "kode produk",
    priceChangeDate: "tanggal",
    selectDate: "pilih tanggal",
    uploadEndDate: "unggah tanggal selesai",
    productType: "kode produk",
    price3: "harga tingkat ketiga",
    baokaPrice: "harga",
    nameNotBlank: "nama tidakboleh kosong",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  priceChangeImeDetail: {
    priceChangeImeDetail: "Harga string editing kode.",
    priceChangeName: "Harga proyek",
    type: "jenis",
    ime: "string kode",
    shopName: "toko",
    imagefile: "gambar",
    clickUpload: "pilih unggah",
    uploadImageSizeFor5000KB: "unggah foto dibawah 500kb",
    pass: "konfirmasi",
    auditRemarks: "keterangan pemeriksaan",
    save: "simpan",
    filter: "saring",
    remarks: "keterangan / komen",
  },
  priceChangeImeForm: {
    priceChangeImeForm: "调价串码上传",
    priceChangeId: "调价项目",
    selectPriceChangeId: "请选择调价项目",
    shopName: "门店",
    ime: "串码",
    nameNotBlank: "名称不能为空",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  priceChangeImeList: {
    priceChangeImeList: "alokasi string kode",
    ime: "string kdoe",
    saleDate: "tanggal",
    type: "tipe",
    areaName: "area",
    officeName: "Afiliasi",
    shopName: "toko",
    priceChangeName: "Harga proyek",
    auditDate: "waktu pemrosesan",
    status: "status",
    pass: "konfirmasi",
    isCheck: "Apakah sampel",
    image: "gambar",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah",
    upload:"meng-upload",
  },
  priceChangeList: {
    priceChangeList: "调价项目",
    name: "nama",
    productType: "nama produk",
    checkPercent: "rasio Sampling",
    priceChangeDate: "alokasi tanggal",
    uploadEndDate: "unggah tanggal selesai",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  pricesystemChangeForm: {
    pricesystemChangeForm: "货品调价编辑",
    product: "产品",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  pricesystemChangeList: {
    pricesystemChangeList: "alokasi barang",
    batchPass: "konfirmasi",
    productName: "barang",
    pricesystemName: "sistem harga",
    oldPrice: "sebelum tranfser",
    newPrice: "sesudah transfer",
    status: "status",
    pass: "konfirmasi",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  productImeList: {
    productImeList: "daftar string kdoe",
    selectInputType: "pilih jenis input",
    ime: "string kdoe",
    ime2: "string kode 2",
    meid: "meid ?",
    retailDate: "tanggal",
    saleDate: "pilih tanggal",
    uploadDate: "tanggal unggah",
    depotName: "gudang",
    netType: "jenis",
    productType: "kode produk",
    inputType: "jenis input",
    createdTime: "dibuat di tanggal",
    boxIme: "nomor kotak pos",
    mutilIme: "string kdoe",
    retailDateBtw: "tanggal",
    createTimeBtw: "dibuat ditanggal",
    meids: "meid",
    month: "penialaian bulanan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  productImeSaleForm: {
    productImeSaleForm: "verifikasi string kode",
    ime: "d=string kode",
    inputIme: "input string kdoe",
    shopId: "verifikasi toko",
    buyer: "akun pelanggan",
    buyerAge: "usia",
    buyerSex: "jenis kelamin",
    man: "laki-laki",
    women: "perempuan",
    buyerPhone: "nomor telepon",
    buyerSchool: "pendidikan",
    buyerGrade: "peringkat",
    name: "nama",
    qty: "kuantitas",
    depotName: "gudang",
    productType: "kode produk",
    baokaDate: "tanggal",
    shopName: "verifikasi toko",
    createdFullName: "verifikasi karyawan",
    createdDate: "verfikasi tangga;",
    imeNotBlank: "string kode tidak boleh kosong",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  productImeSaleList: {
    productImeSaleList: "verfikasi string kode",
    saleShopName: "verifikasi toko",
    ime: "string kode",
    saleDate: "verifikasi tanggal",
    productName: "nama produk",
    employeeName: "verifikasi karyawan",
    isBack: "apakah di kebambalikan",
    name: "nama",
    shopName: "toko",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  productImeUploadForm: {
    productImeUploadForm: "laporan string kode",
    ime: "string kode",
    inputIme: "input string kode",
    month: "penilaian bulanan",
    selectDate: "pilih tanggal",
    shopId: "toko",
    saleEmployee: "promotor",
    name: "nama",
    qty: "kuantitas",
    depotName: "gudang",
    productName: "kode produk",
    retailDate: "tanggal",
    saleShopName: "verifikasi toko",
    saleCreatedFullName: "verifikasi karyawan",
    saleCreatedDate: "verifikasi tanggal",
    uploadShopName: "laporan toko",
    updateDate: "tanggal laporan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  productImeUploadList: {
    productImeUploadList: "laporan string kode",
    batchPass: "konfirmasi",
    month: "penilaian bulanan",
    updateShopName: "laporan toko",
    ime: "string kode",
    updateDate: "tanggal laporan",
    employeeName: "laporan karyawan",
    status: "laporan status",
    pass: "konfirmasi",
    officeId: "departemen",
    shopName: "toko",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  productMonthPriceForm: {
    productMonthPriceForm: "Harga bulanan Mengedit",
    month: "月份",
    selectDate: "pilih tanggal",
    totalName: "nama",
    baokaPrice: "harga",
    price3: "harga tingkat ketiga",
    price2: "Harga jual",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "必填信息",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  productMonthPriceList: {
    productMonthPriceList: "penilaian bulanan",
    id: "ID",
    month: "penilaian bulanan,",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  reportScoreAreaList: {
    reportScoreAreaList: "Peringkat Kantor Urusan",
    reportScoreOfficeRank: "Ranking penilaian Regional",
    scoreDate: "tanggal",
    officeName: "nama kantor",
    score: "penilaian",
    monthScore: "penilaian bulanan",
    dateRank: "tangal peringkat",
    monthRank: "peringkat bulanan",
    saleQty: "kuantitas penjualan",
    monthSaleQty: "kuantitas penjualan bulanan",
    recentMonthSaleQty: "kuantitas penjualan bulanan belakangan ini",
    point: "inti",
    monthSaleMoney: "uang bulanan",
    pointMonthSaleMoney: "uang bulanan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  reportScoreForm: {
    reportScoreForm: "Tingkat harian edit",
    scoreDate: "tanggal",
    selectScoreDate: "pilih Tingkat harian edit",
    companyScore: "penilaian perusahaan",
    companyMonthScore: "enilaian perusahaan bulanan",
    cardQty: "kuantitas kartu",
    monthCardQty: "kuantitas kartu bulanan",
    rank: "peringkat",
    productNames: "nama produk",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  reportScoreList: {
    reportScoreList: "peringkat harian",
    scoreDate: "tanggal",
    companyScore: "peringkat perusahaan",
    companyMonthScore: "peringkat perusahan bulanan",
    score: "penilaian",
    monthScore: "penilaian bulanan",
    cardQty: "kuantitas kartu",
    monthCardQty: "kuantitas kartu bulanan",
    rank: "peringkat",
    saleQty: "penjualan",
    monthSaleQty: "penjualan bulanan",
    recentMonthSaleQty: "penjualan bulanan belakangan ini",
    saleMoney: "uang bulanan",
    monthSaleMoney: "uang bulanan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  reportScoreOfficeList: {
    reportScoreOfficeList: "Peringkat Harian",
    officeRank: "peringkat kantor",
    scoreDate: "tanggal",
    officeName: "nama kantor",
    areaName: "area",
    score: "penilaian",
    monthScore: "penilaian bulanan",
    dateRank: "tangal peringkat",
    monthRank: "peringkat bulanan",
    saleQty: "kuantitas",
    monthSaleQty: "kuantitas bulanan",
    recentMonthSaleQty: "kuantitas bulanan belakangan ini",
    point: "inti",
    monthSaleMoney: "uang bulanan",
    pointMonthSaleMoney: "uang bulanan",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  storeAllotDetail: {
    storeAllotDetail: "transfer fgudang besar",
    businessId: "kode nota",
    fromStore: "sebelum transfer",
    toStore: "sesudah transfer",
    outCode: "kode keuangan",
    expressOrder: "perusahaan jasa pengiriman",
    productName: "nama produk",
    billQty: "jumlah nota",
    shippedQty: "kuantitas pengiriman",
    createdBy: "创建人",
    createdDate: "创建时间",
    remarks: "备注",
    productIme:"串码",
    productMeid:"Meid",
    sendByName:"发货人",
    sendDate:"发货时间",
  },
  storeAllotForm: {
    storeAllotForm: "transfer gudang besar",
    allotType: "cara alokasi",
    fromStore: "sebelum transfer",
    toStore: "sesudah transfer",
    shipType: "jenis pengiriman",
    expressCompany: "perusahaaan jasa pengiriman",
    syn: "Disinkronkan dengan keuangan",
    productName: "nama produk",
    inputKeyOf100Item: "Cukup masukkan kata kunci, hanya 100 catatan pertama",
    cloudQty: "persediaan keuangan",
    billQty: "jumlah transfer",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    delete: "删除",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid",
    yes:"是",
    no:"否",

  },
  storeAllotList: {
    storeAllotList: "transfer gudang besar",
    businessId: "kode nota",
    fromStore: "sebelum tramnsfer",
    toStore: "sesudah transfer",
    outCode: "kode keluar",
    status: "status",
    add: "tambah",
    filter: "saring",
    export: "ekspor keluar",
    filterOrExport: "saring atau ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "masukkan kata kunci",
    inputWord: "masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "dibuat pada tangga;",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa",
    print:"出库单",
    shipPrint:"快递单",

  },
  storeAllotShip: {
    storeAllotShip: "alokasi gudang besar",
    businessId: "nomor transfer",
    fromStore: "sebelum transfer",
    toStore: "sesudah transfer",
    boxImeStr: "nomor kotak pos",
    imeStr: "string kode",
    expressCodes: "kode resi",
    productName: "货品名称",
    hasIme: "包含串码",
    remarks: "keterangan",
    billQty: "jumlah nota",
    shippedQty: "jumlah pengiriman barang",
    waitShipQty: "jumlah pengiriman yang masih menunggu",
    shipQty: "jumlah pengiriman barang"
  }
}
