export default {
  adPricesystemForm: {
    adPricesystemForm: "BAHAN PENGIRIMAN",
    name: "NAMA",
    isAdPricesystem: "INI TERMASUK DALAM KATEGORI",
    officeName: "agen",
    areaName: "area",
    typeLabel: "daftar toko",
    chainName: "sistem rantai",
    areaType: "tipe area",
    office: "机构",
    adPricesystem: "biaya pengiriman etalase",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  adPricesystemList: {
    adPricesystemList: "biaya pengiriman etalase",
    name: "名称",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  bankForm: {
    bankForm: "formulir bank",
    name: "nama",
    account: "akun",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid,"
  },
  bankList: {
    bankList: "daftar bank",
    syn: "sinkronisasi",
    name: "nama",
    code: "kode",
    account: "akun",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  chainForm: {
    chainForm: "Sistem rantai editing",
    name: "nama",
    account: "akun",
    officeName: "nama kantor",
    isAdPricesystem: "是否属于该类别",
    areaName: "area",
    shopType: "jenis",
    chainName: "nama rantai",
    areaType: "area",
    adPricesystemName: "物料运费",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  chainList: {
    chainList: "DAFTAR RANTAI",
    name: "daftar",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  dealerForm: {
    dealerForm: "formulir dealer",
    loginName: "username",
    name: "nama",
    mobilePhone: "nomor telepon",
    password: "kata sandi",
    confirmPassword: "konfirmasi kata sandi",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  dealerList: {
    dealerList: "manajemen dealer",
    name: "nama",
    mobilePhone: "nomor telepon",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  demoPhoneTypeForm: {
    demoPhoneTypeForm: "formulir demo mesin",
    name: "nama",
    productType: "jenis",
    limitQty: "kuota mesin demo",
    applyEndDate: "tanggal",
    renewEndDate: "reset tanggal",
    officeName: "nama kantor",
    taskPoint: "inti tugas",
    qty: "jumlah",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  demoPhoneTypeList: {
    demoPhoneTypeList: "demo mesin",
    name: "nama",
    productTypeNames: "jenis",
    limitQty: "kuota mesin demo",
    applyEndDate: "tanggal",
    renewEndDate: "reset tanggal",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  depotForm: {
    depotForm: "manajemen gudang",
    shopType: "jenis toko",
    selectType: "pilih jenis",
    officeName: "lembaga",
    name: "nama",
    taxName: "nama pajak",
    reportName: "daftar nama",
    storeName: "nama gudang",
    inputKeyOf20Item: "Cukup masukkan kata kunci sebelum 20, acara",
    shopName: "nama toko",
    contact: "kontak",
    mobilePhone: "hape",
    address: "alamat",
    forSaleMan: "Binding promotor",
    areaType: "Tipe daerah",
    businessCenter: "Apakah kawasan bisnis inti",
    true: "benar",
    false: "salah",
    businessCenterName: "Inti nama kawasan bisnis",
    channelType: "Operator saluran sosial",
    salePointType: "atribut toko",
    specialityStoreType: "Jenis Toko",
    chainType: "jenis rantai",
    carrierType: "jenis karir",
    turnoverType: "penjualan properti",
    specialityStore: "Apakah Pengalaman Toko",
    district: "daerah",
    doorHead: "Apakah ada pintu pertama",
    enableDate: "tanggal",
    dealerName: "nama dealer",
    pricesystem: "sistem harga",
    chain: "sistem rantai",
    shopArea: "aera",
    frameNum: "2_0 nomor frame suspensi",
    cabinetNum: "Showcase nomor",
    deskDoubleNum: "2_0 nomor frame suspensi",
    deskSingleNum: "2_0 nomor frame suspensi",
    townName: "",
    cmccCarrierShop: "Toko mal nomor mobile station",
    ctccCarrierShop: "AlliedSignal Mall nama toko",
    hasGuide: "Memiliki panduan belanja",
    rebate: "Yang tidak ada",
    printPrice: "Tarif cetak Pengiriman",
    isHidden: "Tersembunyi",
    adShop: "apakah toko iklan",
    adShopBsc: "Apakah kantor advertising (toko bahan keuangan)",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  depotList: {
    depotList: "manajemen gudangn",
    syn: "sinkronisasi",
    name: "nama",
    officeName: "lembaga",
    areaName: "area",
    typeLabel: "jenis toko",
    xxbzj: "gambar Margin",
    scbzj: "pasar obligasi",
    contact: "kontak",
    mobilePhone: "hape",
    outGroupName: "grup",
    chainName: "sistem rantai",
    pricesystemName: "Grid System",
    adShop: "toko ilan",
    isHidden: "menyembunyikan",
    areaType: "Tipe daerah",
    delegateDepotName: "perpustakaan konsinyasi",
    townType: "tipe kota",
    credit: "kredit",
    id: "jumlah",
    outCode: "encoder eksternal",
    expressCompany: "perusahaan jasa pengiriman",
    rebate: "dengan rabat",
    specialityStore: "是否体验店",
    specialityStoreType: "专卖店类型",
    adPricesystemId: "物料运费",
    districtName: "行政区域",
    isAdShopBsc: "是否广告办事处",
    isAdShop: "是否广告门店",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  expressCompanyForm: {
    expressCompanyForm: "Ekspres Mengedit",
    name: "nama",
    expressType: "jenis",
    district: "daerah",
    reachPlace: "Pengiriman lokasi",
    shouldGetRule: "Pengiriman Aturan",
    address: "alamat",
    contact: "kontak",
    phone: "telepon",
    mobilePhone: "hape",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    selectType: "请选择类型",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  expressCompanyList: {
    expressCompanyList: "perusahan=an jasa pengiriman",
    name: "nama",
    expressType: "jenis",
    reachPlace: "lokasi pengiriman",
    shouldGetRule: "Pengiriman Aturan",
    address: "alamat",
    contact: "kontak",
    phone: "telepon",
    mobilePhone: "hape",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  pricesystemForm: {
    pricesystemForm: "Harga Sistem Edit",
    name: "nama",
    sort: "penurutan",
    input2Key: "至少2位关键字",
    productName: "nama barang",
    price: "harga",
    priceRequestNumber: "Harga harus nilai numerik",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  pricesystemList: {
    pricesystemList: "sistem harga",
    toSee: "sekilas",
    name: "nama",
    sort: "pengurutan",
    isIme: "string kode gudang",
    code: "kode",
    allowBill: "Memungkinkan penagihan",
    productType: "Model produk",
    allowOrder: "memungkinkan pemesanan",
    outGroupName: "nama produk",
    netType: "jenis",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  productList: {
    productList: "manajemen barang",
    productEdit: "manajemen bahan",
    syn: "sinkronisasi",
    name: "nama",
    code: "kode",
    netType: "jenis",
    outGroupId: "perbedaan coding",
    outGroupName: "jenis produk",
    productType: "kode produk",
    hasIme: "string kode",
    allowOrder: "memungkinkan Pemesanan",
    allowBill: "memungkinkan buka nota",
    image: "gambar",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  productForm: {
    productForm: "manajemen barang",
    name: "nama barang",
    code: "kode",
    outGroupName: "jenis produk",
    productTypeName: "kode produk",
    netType: "jenis",
    select: "pilih",
    hasIme: "string kode gudang",
    allowOrder: "memungkinkan pemesanan",
    allowBill: "Memungkinkan penagihan",
    true: "benar",
    false: "salah",
    price2: "harga tingkat kedua",
    retailPrice: "harga ecer",
    depositPrice: "harga deposit",
    mappingName: "nama service center",
    image: "gambar",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid,"
  },
  productAdEdit: {
    productAdEdit: "Material Editor",
    code: "kode",
    name: "nama",
    visible: "terlihat",
    allowOrder: "memungkinkan pemesanan",
    price2: "harga tingkat kedua",
    expiryDateRemarks: "keterangan tanggal jatuh tempo",
    volume: "volume",
    hasIme: "string kode",
    allowBill: "Memungkinkan penagihan",
    productType: "Model produk",
    outGroupName: 'nama produk',
    netType: "jenis",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  productTypeForm: {
    productTypeForm: "Statistik Model Editor",
    name: "名称",
    reportName: "nama tabel",
    product: "produk",
    code: "kode",
    baokaPrice: "harga",
    scoreType: "jenis penilaian",
    true: "benar",
    false: "salah",
    price1: "harga satuan",
    price2: "Harga jual",
    price3: "三级价",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  productTypeList: {
    productTypeList: "model statistik",
    name: "名称",
    reportName: "Nama laporan",
    code: "编码",
    productNames: "nama barang",
    price1: "harga",
    scoreType: "jenis penilaian",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "模糊搜索",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  shopAdTypeForm: {
    shopAdTypeForm: "Jenis Iklan Edit",
    totalPriceType: "Perhitungan harga Type",
    name: "nama",
    price: "harga",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  shopAdTypeList: {
    shopAdTypeList: "jenis iklan",
    totalPriceType: "harga",
    name: "nama",
    price: "harga",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
}
