export default {
  menus: {
    backend:{
      basicManager:"基础管理",
      businessManager:"业务管理",
      cloudManager:"金蝶管理",
      factoryManager:"工厂对接",
    },
    backendModule:{
      basicSysModule:"系统",
      basicHrModule:"人事",
      businessBasicModule:"基础",
      businessWorkModule:"业务",
      businessPlanningModule:"企划",
      businessReportModule:"报表",
      cloudReportModule:"报表",
      cloudInputModule:"录单",
      cloudSysModule:"系统",
      factoryBasicModule:"基础",
    },
    menuCategory:{
      hrCategory:"人事管理",
      sysCategory:"系统设置",
      saleCategory:"销售管理",
      wagesCategory:"薪资核算",
      apiCategory:"外部接口",
      menusCategory:"菜单",
      officeCategory:"组织机构",
      dictCategory:"字典",
      permissionCategory:"权限",
      fileCategory:"文件",
      dutyCategory:"勤务管理",
      workStreamCategory:"工作流",
      taskCenterCategory:"任务中心",
      accountAboutCategory:"员工相关",
      salCategory:"工资管理",
      productImeCategory:"货品串码",
      baseCategory:"基础资料",
      adCategory:"物料广告",
      customerCategory:"客服中心",
      afterSaleCategory:"售后管理",
      saleReportCategory:"销售报表",
      k3CloudCategory:"K3Cloud",
      b2bCategory:"移动商城",
      oppoDataCategory:"OPPO数据",
      dataManagerCategory:"数据管理",
      vivoDataCategory:"vivo数据",
      taskPolicyCategory:"任务政策",
      commissionCategory:"提成基准",
      reportCategory:"报表中心",
      cloudBatchBillCategory:"批量录入",
      cloudReportCategory:"财务报表",
      cloudSysCategory:"系统设置"
    },
    menu:{
      monitor: "laporan pemantauan",
      menuCategory: "klasifikasi pilihan",
      menusCategory: "pilihan",
      officeCategory: "organisasi",
      dictCategory: "kamus",
      permissionCategory: "kompetensi",
      fileCategory: "berkas",
      dutyCategory: "layanan manajemen",
      workStreamCategory: "arus kerja",
      taskCenterCategory: "tugas pusat",
      accountAboutCategory: "departemen terkait",
      salCategory: "工资管理",
      productImeCategory: "barang string kode",
      baseCategory: "manajemen gaji",
      orderCategory: "manajemen pemesanan barang",
      adCategory: "iklan bahan",
      customerCategory: "pusat layanan pelanggan",
      afterSaleCategory: "manajemen penjualan",
      saleReportCategory: "laporan penjualan",
      k3CloudCategory: "K3Cloud",
      dataManagerList:"数据管理4",
      b2bCategory: "移动商城",
      oppoDataCategory: "OPPO data",
      vivoDataCategory: "VIVO data",
      taskPolicyCategory: "kebijakan tugas",
      commissionCategory: "referensi komisi",
      reportCategory: "laporan pusat",
      hrCategory: "manajemen personalia",
      sysCategory: "pengaturan sistem",
      saleCategory: "manajemen penjualan",
      wagesCategory: "payroll",
      apiCategory: "pertemuan eksternal",
      cloudInputCategory:"财务录单",
      cloudBatchBillCategory:"批量录入",
      salOutStock:"出库单",
      salReturnStock:"退货单",
      stkMisDelivery:'其他出库',
      cloudReportCategory:"财务报表",
      payableReport:"应付对账报表",
      customerReceive:"应收对账报表",
      consignmentReport:"委托代销报表",
      retailReport:"零售报表",
      cloudSysCategory:"系统设置",
      kingdeeBookList:"账套管理",
      kingdeeBookForm:"账套编辑",
      accountKingdeeBookList:"金蝶用户管理",
      404:"404",
      companyConfigForm: "Preferensi Editor",
      companyConfigList: "Pengaturan parameter",
      dictEnumForm: "Enum Kamus Editor",
      dictEnumList: "pencacahan kamus",
      dictMapForm: "Key Kamus Editor",
      dictMapList: "Kamus kunci",
      folderFileList: "Manajemen File",
      folderForm: "mengedit direktori file",
      folderList: "daftar folder",
      home:"home",
      menuCategoryForm: "mengubah pilihan grup",
      menuCategoryList: "daftar kategori pilihan",
      menuForm: "formulir pilihan",
      menuList: "daftar menu",
      permissionForm: "formulir perizinan",
      permissionList: "IZIN",
      processList: "DAFTAR PROSES",
      processTypeForm: "Proses Editor dinamis",
      processTypeList: "DAFTRA TIPE PROSES",
      accountChangeForm: "FORMULIR PERUBAHAN AKUN",
      accountChangeList: "员工调整",
      accountForm: "FORMULIR AKUN",
      accountList: "Manajemen akun",
      accountTaskList: "待办事项",
      auditFileDetail: "Rincian persetujuan dokumen",
      auditFileForm: "periksan formulir berkas",
      auditFileList: "Dokumen persetujuan",
      dutyAnnualForm: "formulir tahunan",
      dutyAnnualList: "daftar tahunan",
      dutyFreeList: "免打考勤",
      dutyLeaveList: "formulir cuti",
      dutyOvertimeList: "formulir lembur",
      dutyPublicFreeList: "manajemen cuti",
      dutyRestList: "formulir libur",
      dutySignList: "daftar check",
      dutyTaskForm: "Layanan editing persetujuan",
      dutyTaskList: "layanan persetujuan",
      dutyTripList: "formulir dinas",
      dutyWorktimeForm: "Pukulan Rekam Edit",
      dutyWorktimeList: "打卡记录",
      employeeEditForm: "信息修改",
      employeeForm: "formulir karyawan",
      employeeList: "daftar karyawan",
      employeePhoneDepositForm: "formulir deposit karyawan",
      employeePhoneDepositList: "daftar deposit karyawan",
      employeePhoneForm: "edit mesin promotor",
      employeePhoneList: "handphone promotor",
      jobForm: "formulir ppekerjaan",
      jobList: "formulir ppekerjaan",
      officeForm: "formulir kantor",
      officeList: "daftar kantor",
      positionForm: "formulir jabatan",
      positionList: "daftar jabatan",
      recruitBatchForm:"招聘信息批量编辑",
      recruitForm: "formulir perekrutan",
      recruitList: "daftar perekrutan",
      adApplyBillForm: "formulir nota",
      adApplyForm: "formulir bahan",
      adApplyGoods: "POP分货",
      adApplyList: "daftar bahan",
      adGoodsOrderBill: "buka nota bahan",
      adGoodsOrderDetail: "perincian bahan",
      adGoodsOrderForm: "orderan etalase",
      adGoodsOrderList: "pemesanan etalase",
      adGoodsOrderShip: "order bahan",
      adGoodsOrderSign: "order barang",
      adPricesystemChangeForm: "formulir",
      adPricesystemChangeList: "Pengiriman Edit",
      adPricesystemForm: "BAHAN PENGIRIMAN",
      adPricesystemList: "biaya pengiriman etalase",
      afterSaleAreaEdit: "setelah penjualan",
      afterSaleEditForm: "formulir service center",
      afterSaleForm: "formulir service center",
      afterSaleFromCompany: "gudang barang bagus",
      afterSaleImeAllotList: "daftar alokasi",
      afterSaleList: "tabel service center",
      afterSaleProductAllotList: "service center",
      afterSaleStoreAllotList: "service center",
      afterSaleToCompany: "坏机返厂",
      bankForm: "formulir bank",
      bankInDetail: "kredit penjualan",
      bankInForm: "tambah kredit penjualan",
      bankInList: "kredit penjualan",
      bankList: "daftar bank",
      chainForm: "Sistem rantai editing",
      chainList: "DAFTAR RANTAI",
      dataReportList: "daftar data",
      clientForm: "formulir client",
      clientList: "manajemen client",
      demoPhoneForm: "demo memakai mesin",
      demoPhoneList: "demo mesin",
      demoPhoneTypeForm: "formulir demo mesin",
      demoPhoneTypeList: "demo mesin",
      depotAccountDetail: "Akun Laporan Detail",
      depotAccountList: "akun laporan",
      depotChangeDetail: "Rincian penyesuaian gudang",
      depotChangeForm: "formulir gudang",
      depotChangeList: "仓库调整",
      depotDetailList: "persediaan barang",
      depotForm: "manajemen gudang",
      depotList: "manajemen gudangn",
      expressCompanyForm: "Ekspres Mengedit",
      expressCompanyList: "perusahan=an jasa pengiriman",
      expressForm: "Ekspres managing editor",
      expressList: "manajemen pengiriman",
      expressOrderForm: "Mengungkapkan Percetakan Editing",
      expressOrderList: "daftar jasa pengiriman",
      goodsOrderBill: "pengiriman barang",
      goodsOrderDetail: "货品订货详细",
      goodsOrderForm: "pengiriman barang",
      goodsOrderList: "pengiriman barang",
      goodsOrderShip: "pengiriman barnag",
      goodsOrderSign: "订单签收",
      goodsOrderSreturn: "销售退货",
      imeAllotForm: "Alokasi mengedit string kode",
      imeAllotList: "alokasi string kode",
      priceChangeDetail: "Proyek sampel Harga",
      priceChangeForm: "Harga mengedit proyek",
      priceChangeImeDetail: "Harga string editing kode.",
      priceChangeImeForm: "调价串码上传",
      priceChangeImeList: "alokasi string kode",
      priceChangeList: "调价项目",
      pricesystemChangeForm: "货品调价编辑",
      pricesystemChangeList: "alokasi barang",
      pricesystemForm: "Harga Sistem Edit",
      pricesystemList: "sistem harga",
      productAdEdit: "Material Editor",
      productForm: "manajemen barang",
      productImeList: "daftar string kdoe",
      productImeSaleForm: "verifikasi string kode",
      productImeSaleList: "verfikasi string kode",
      productImeUploadForm: "laporan string kode",
      productImeUploadList: "laporan string kode",
      productList: "manajemen barang",
      productEdit: "manajemen bahan",
      productMonthPriceForm: "Harga bulanan Mengedit",
      productMonthPriceList: "penilaian bulanan",
      productTypeForm: "Statistik Model Editor",
      productTypeList: "model statistik",
      reportScoreAreaList: "Peringkat Kantor Urusan",
      reportScoreOfficeRank: "Ranking penilaian Regional",
      reportScoreForm: "Tingkat harian edit",
      reportScoreList: "peringkat harian",
      reportScoreOfficeList: "Peringkat Harian",
      shopAdDetail: "formulir iklan",
      shopAdForm: "formulir iklan",
      shopAdList: "formulir iklan",
      shopAdTypeForm: "Jenis Iklan Edit",
      shopAdTypeList: "jenis iklan",
      shopAllotDetail: "Toko alokasi editing",
      shopAllotForm: "tambah alokasi toko",
      shopAllotList: "alokasi toko",
      shopBuildDetail: "Detail konstruksi toko",
      shopBuildForm: "Mengedit konstruksi toko",
      shopBuildList: "konstruksi toko",
      shopDepositForm: "daftar deposit",
      shopDepositList: "daftar deposit",
      shopGoodsDepositForm: "piutang deposit",
      shopGoodsDepositList: "piutang deposit",
      shopImageForm: "Mengganti image editor",
      shopImageList: "penggantian gambar",
      shopPrintDetail: "perincian cetak periklanan",
      shopPrintForm: "formulir cetak periklanan",
      shopPrintList: "cetak periklanan",
      shopPromotionForm: "活动拉销编辑",
      shopPromotionList: "活动拉销",
      storeAllotDetail: "transfer fgudang besar",
      storeAllotForm: "transfer gudang besar",
      storeAllotList: "transfer gudang besar",
      storeAllotShip: "alokasi gudang besar",
      dutySignAddList:"补签申请",
      companyList: '公司管理',
      companyForm: '公司管理编辑',
      officeChangeList: '机构调整',
      officeChangeForm: '机构调整编辑',
      officeChangeDetail: '机构调整详细',
      noticeList: '公告列表',
      noticeForm: '公告列表编辑',
      noticeDetail: '公告列表详细',
      accountMessageList: '私信列表',
      accountMessageForm: '私信列表编辑',
      accountMessageDetail: '私信列表详细',
      employeeSalaryBasicList: '工资模版',
      employeeSalaryBasicForm: '工资模版编辑',
      employeeSalaryBasicDetail: '工资模版详细',
      employeeSalaryList: '工资列表',
      employeeSalaryForm: '工资列表编辑',
      stockCheckList: '库存盘点',
      stockCheckForm: '库存盘点编辑',
      stockCheckDetail: '库存盘点详细',
      helpFaqTypeList: '问答分组',
      helpFaqTypeForm: '问答分组编辑',
      helpQuestionList: '个人提问',
      helpQuestionForm: '个人提问编辑',
      helpQuestionDetail: '个人提问详细',
      helpFaqList: '问答列表',
      helpFaqForm: '问答列表编辑',
      helpFaqDetail: '问答详细',
      articleList: '文章管理',
      articleForm: '文章管理编辑',
      articleDetail: '文章管理详细',
      lotteryRuleList: '抽奖管理',
      lotteryRuleForm: '抽奖管理编辑',
      k3CloudGlVoucherList: '凭证列表',
      k3CloudGlVoucherForm: '凭证录入',
      k3CloudGlVoucherDetail: '凭证详细',
      carrierShopList: '商城门店',
      carrierShopForm: '商城门店编辑',
      carrierProductList: '商城货品',
      carrierProductForm: '商城货品编辑',
      carrierOrderList: '商城订单',
      carrierOrderForm: '商城订单编辑',
      carrierShip: '商城订单发货',
      oppoPlantProductsList: 'OPPO物料编码',
      oppoPlantElectronicList: 'OPPO电子保卡',
      oppoProductsList: 'OPPO颜色编码',
      oppoPlantSendImeList: 'OPPO发货串码',
      vivoPlantProductsList: 'vivo物料编码',
      vivoPlantElectronicList: 'vivo电子保卡',
      vivoProductsList: 'vivo颜色编码',
      vivoPlantSendImeList: 'vivo发货串码',
      productImeStockReport: '库存报表',
      productMonthPriceSum: '保卡统计',
      salaryTemplateList: '工资项目',
      salaryTemplateForm: '工资项目编辑',
      salaryList: '我的工资',
      salaryForm: '我的工资编辑',
      imooPlantProductsList:'Imoo物料编码',
      imooPlantSendImeList:'Imoo发货串码',
      reportCenterTable:'报表中心（表）',
      reportCenterCharts:'报表中心（图）',
      k3cloudCheckOutStock:'出库核对',
      k3cloudCheckOutStockDetail:'出库核对详细',
      cloudSynList:'金蝶核对',
      cloudSynDetail:'金蝶核对详细',
      localizationList:'国际化设置',
      dutyTimeSearchList:'考勤查询',
      employeePointSearchList:'积分查询',
      employeeExpenseList:'费用报销',
      employeeSaleReport:'员工报表',
      productImeUploadReport:'上报报表',
      goodsOrderShipList:'仓库发货',
      productImeSearchList:'串码查询',
      shopAttributeList:'终端统计',
      productImeSaleReport:'销售报表',
      depotInventoryReport:'门店报表',
      b2bForm:'移动订货',
      taskProductTypeList:'任务机型',
      taskAreaList:'办事处任务',
      taskOfficeList:'考核区域任务',
      taskDetailList:'门店任务',
      taskPolicyList:'政策管理',
      areaCommissionList:'办事处提成',
      basicCommissionList:'提成基准',
      priceChangeCommissionList:'调价提成',
      //delete
      hrrecruit:"无效",
      officeUnitsEdit:'单元编辑',
      officeRule:'部门规则',
      backendModuleList:'项目模块',
      backendList:'项目管理',
    }
  }
}
