export default {
  menus: {
    backend:{
      basicManager:"基础管理",
      businessManager:"业务管理",
      cloudManager:"金蝶管理",
      factoryManager:"工厂对接",
    },
    backendModule:{
      basicSysModule:"系统",
      basicHrModule:"人事",
      businessBasicModule:"基础",
      businessWorkModule:"业务",
      businessPlanningModule:"企划",
      businessReportModule:"报表",
      cloudReportModule:"报表",
      cloudInputModule:"录单",
      cloudSysModule:"系统",
      factoryBasicModule:"基础",
    },
    menuCategory:{
      hrCategory:"人事管理",
      sysCategory:"系统设置",
      saleCategory:"销售管理",
      wagesCategory:"薪资核算",
      apiCategory:"外部接口",
      menusCategory:"菜单",
      officeCategory:"组织机构",
      dictCategory:"字典",
      permissionCategory:"权限",
      fileCategory:"文件",
      dutyCategory:"勤务管理",
      workStreamCategory:"工作流",
      taskCenterCategory:"任务中心",
      accountAboutCategory:"员工相关",
      salCategory:"工资管理",
      productImeCategory:"货品串码",
      baseCategory:"基础资料",
      adCategory:"物料广告",
      customerCategory:"客服中心",
      afterSaleCategory:"售后管理",
      saleReportCategory:"销售报表",
      k3CloudCategory:"K3Cloud",
      b2bCategory:"移动商城",
      oppoDataCategory:"OPPO数据",
      dataManagerCategory:"数据管理",
      vivoDataCategory:"vivo数据",
      taskPolicyCategory:"任务政策",
      commissionCategory:"提成基准",
      reportCategory:"报表中心",
      cloudBatchBillCategory:"批量录入",
      cloudReportCategory:"财务报表",
      cloudSysCategory:"系统设置",
      goodsOrderCategory:"订货管理",
    },
    menu:{
      monitor:"报表监控",
      menuCategory:"菜单分组",
      menusCategory:"菜单",
      officeCategory:"组织机构",
      dictCategory:"字典",
      permissionCategory:"权限",
      fileCategory:"文件",
      dutyCategory:"勤务管理",
      workStreamCategory:"工作流",
      taskCenterCategory:"任务中心",
      accountAboutCategory:"员工相关",
      salCategory:"工资管理",
      productImeCategory:"货品串码",
      baseCategory:"基础资料",
      orderCategory:"订货管理",
      adCategory:"物料广告",
      customerCategory:"客服中心",
      afterSaleCategory:"售后管理",
      saleReportCategory:"销售报表",
      k3CloudCategory:"K3Cloud",
      dataManagerList:"数据管理4",
      b2bCategory:"移动商城",
      oppoDataCategory:"OPPO数据",
      vivoDataCategory:"vivo数据",
      taskPolicyCategory:"任务政策",
      commissionCategory:"提成基准",
      reportCategory:"报表中心",
      hrCategory:"人事管理",
      sysCategory:"系统设置",
      saleCategory:"销售管理",
      wagesCategory:"薪资核算",
      apiCategory:"外部接口",
      cloudInputCategory:"财务录单",
      cloudBatchBillCategory:"批量录入",
      salOutStock:"销售出库单",
      salReturnStock:"销售退货单",
      stkMisDelivery:'其他出库',
      cnJournalForCash:'现金存款日记账',
      cloudReportCategory:"财务报表",
      payableReport:"应付对账报表",
      customerReceive:"应收对账报表",
      consignmentReport:"委托代销报表",
      retailReport:"零售报表",
      cloudSysCategory:"系统设置",
      kingdeeBookList:"账套管理",
      kingdeeBookForm:"账套编辑",
      accountKingdeeBookList:"金蝶用户管理",
      accountKingdeeBookForm:"金蝶用户管理编辑",
      productManager:"货品管理",
      404: "404",
      companyConfigForm: "参数设置编辑",
      companyConfigList: "参数设置",
      dictEnumForm: "枚举字典编辑",
      dictEnumList: "枚举字典",
      dictMapForm: "键值字典编辑",
      dictMapList: "键值字典",
      folderFileList: "文件管理",
      folderForm: "文件目录编辑",
      folderList: "文件目录",
      home: "home",
      menuCategoryForm: "菜单分组编辑",
      menuCategoryList: "菜单分组",
      menuForm: "菜单列表编辑",
      menuList: "菜单列表",
      permissionForm: "权限设置编辑",
      permissionList: "权限设置",
      processList: "流程列表",
      processTypeForm: "动态流程编辑",
      processTypeList: "动态流程",
      accountChangeForm: "员工调整编辑",
      accountChangeList: "员工调整",
      accountForm: "账户管理编辑",
      accountList: "账户管理",
      accountTaskList: "待办事项",
      auditFileDetail: "文件审批详细",
      auditFileForm: "文件审批编辑",
      auditFileList: "文件审批",
      dutyAnnualForm: "年假管理编辑",
      dutyAnnualList: "年假管理",
      dutyFreeList: "免打考勤",
      dutyLeaveList: "请假申请",
      dutyOvertimeList: "加班申请",
      dutyPublicFreeList: "公休管理",
      dutyRestList: "调休申请",
      dutySignList: "签到列表",
      dutyTaskForm: "勤务审批编辑",
      dutyTaskList: "勤务审批",
      dutyTripList: "出差申请",
      dutyWorktimeForm: "打卡记录编辑",
      dutyWorktimeList: "打卡记录",
      employeeEditForm: "信息修改",
      employeeForm: "员工管理编辑",
      employeeList: "员工管理",
      employeePhoneDepositForm: "押金收款编辑",
      employeePhoneDepositList: "押金收款",
      employeePhoneForm: "导购用机编辑",
      employeePhoneList: "导购用机",
      jobForm: "职位管理编辑",
      jobList: "职位管理",
      officeForm: "机构管理编辑",
      officeList: "机构管理",
      positionForm: "岗位管理编辑",
      positionList: "岗位管理",
      recruitBatchForm: "招聘信息批量编辑",
      recruitForm: "招聘信息编辑",
      recruitList: "招聘信息",
      adApplyBillForm: "POP开单申请",
      adApplyForm: "POP申请",
      adApplyGoods: "POP分货",
      adApplyList: "POP征订",
      adGoodsOrderBill: "柜台订货开单",
      adGoodsOrderDetail: "柜台订货详细",
      adGoodsOrderForm: "物料订单编辑",
      adGoodsOrderList: "柜台订货",
      adGoodsOrderShip: "柜台订货发货",
      adGoodsOrderSign: "货品订货详细",
      adPricesystemChangeForm: "物料运费调整申请",
      adPricesystemChangeList: "运费修改",
      adPricesystemForm: "物料运费编辑",
      adPricesystemList: "物料运费",
      afterSaleAreaEdit: "垫机录入",
      afterSaleEditForm: "售后申请编辑",
      afterSaleForm: "售后申请",
      afterSaleFromCompany: "好机返库",
      afterSaleImeAllotList: "调拨列表",
      afterSaleList: "售后列表",
      afterSaleProductAllotList: "售后盘点",
      afterSaleStoreAllotList: "售后调拨",
      afterSaleToCompany: "坏机返厂",
      bankForm: "银行列表编辑",
      bankInDetail: "销售收款编辑",
      bankInForm: "销售收款添加",
      bankInList: "销售收款",
      bankList: "银行列表",
      chainForm: "连锁体系编辑",
      chainList: "连锁体系",
      dataReportList: "合计报表",
      clientForm: "客户管理编辑",
      clientList: "客户管理",
      demoPhoneForm: "演示用机编辑",
      demoPhoneList: "演示用机",
      demoPhoneTypeForm: "演示机型编辑",
      demoPhoneTypeList: "演示机型",
      demoPhoneTypeOfficeList:"演示机型汇总",
      depotAccountDetail: "应收报表详细",
      depotAccountList: "应收报表",
      depotChangeDetail: "仓库调整详细",
      depotChangeForm: "仓库调整编辑",
      depotChangeList: "仓库调整",
      depotDetailList: "货品库存",
      depotForm: "仓库管理编辑",
      depotList: "仓库管理",
      expressCompanyForm: "快递公司编辑",
      expressCompanyList: "快递公司",
      expressForm: "快递管理编辑",
      expressList: "快递管理",
      expressOrderForm: "快递打印编辑",
      expressOrderList: "快递打印",
      goodsOrderBill: "货品订货开单",
      goodsOrderDetail: "货品订货详细",
      goodsOrderForm: "货品订货编辑",
      goodsOrderList: "货品订货",
      goodsOrderShip: "货品订货发货",
      goodsOrderShipList: "货品发货",
      goodsOrderSign: "订单签收",
      goodsOrderSreturn: "销售退货",
      imeAllotForm: "串码调拨编辑",
      imeAllotList: "串码调拨",
      priceChangeDetail: "调价项目抽检",
      priceChangeForm: "调价项目编辑",
      priceChangeImeDetail: "调价串码编辑",
      priceChangeImeForm: "调价串码上传",
      priceChangeImeList: "调价串码",
      priceChangeList: "调价项目",
      pricesystemChangeForm: "货品调价编辑",
      pricesystemChangeList: "货品调价",
      pricesystemForm: "价格体系编辑",
      pricesystemList: "价格体系",
      productAdEdit: "物料编辑",
      productForm: "货品管理编辑",
      productImeList: "串码列表",
      productImeDetail: "串码详情",
      productImeSaleForm: "串码核销编辑",
      productImeSaleBackForm: "串码核销退回编辑",
      productImeSaleList: "串码核销",
      productImeUploadForm: "串码上报编辑",
      productImeUploadList: "串码上报",
      productList: "货品管理",
      productEdit: "物料编辑",
      productMonthPriceForm: "每月价格编辑",
      productMonthPriceList: "每月价格",
      productTypeForm: "统计型号编辑",
      productTypeList: "统计型号",
      reportScoreAreaList: "办事处排名",
      reportScoreOfficeRank: "考核区域排名",
      reportScoreForm: "每日打分编辑",
      reportScoreList: "每日打分",
      reportScoreOfficeList: "每日排名",
      shopAdDetail: "广告申请详细",
      shopAdForm: "广告申请编辑",
      shopAdList: "广告申请",
      shopAdTypeForm: "广告类型编辑",
      shopAdTypeList: "广告类型",
      shopAllotDetail: "门店调拨编辑",
      shopAllotForm: "门店调拨添加",
      shopAllotList: "门店调拨",
      shopBuildDetail: "门店建设详细",
      shopBuildForm: "门店建设编辑",
      shopBuildList: "门店建设",
      shopDepositForm: "押金列表编辑",
      shopDepositList: "押金列表",
      shopGoodsDepositForm: "订金收款编辑",
      shopGoodsDepositList: "订金收款",
      shopImageForm: "形象更换编辑",
      shopImageList: "形象更换",
      shopPrintDetail: "广告印刷详细",
      shopPrintForm: "广告印刷编辑",
      shopPrintList: "广告印刷",
      shopPromotionForm: "活动拉销编辑",
      shopPromotionList: "活动拉销",
      storeAllotDetail: "大库调拨详细",
      storeAllotForm: "大库调拨编辑",
      storeAllotList: "大库调拨",
      storeAllotShip: "大库调拨发货",
      storeAllotShipPrint: "大库调拨快递单打印",
      storeAllotPrint: "大库调拨出库单打印",
      dutySignAddList:"补签申请",
      companyList: '公司管理',
      companyForm: '公司管理编辑',
      officeChangeList: '机构调整',
      officeChangeForm: '机构调整编辑',
      officeChangeDetail: '机构调整详细',
      noticeList: '公告列表',
      noticeForm: '公告列表编辑',
      noticeDetail: '公告列表详细',
      accountMessageList: '私信列表',
      accountMessageForm: '私信列表编辑',
      accountMessageDetail: '私信列表详细',
      employeeSalaryBasicList: '工资模版',
      employeeSalaryBasicForm: '工资模版编辑',
      employeeSalaryBasicDetail: '工资模版详细',
      employeeSalaryList: '工资列表',
      employeeSalaryForm: '工资列表编辑',
      stockCheckList: '库存盘点',
      stockCheckForm: '库存盘点编辑',
      stockCheckDetail: '库存盘点详细',
      helpFaqTypeList: '问答分组',
      helpFaqTypeForm: '问答分组编辑',
      helpQuestionList: '个人提问',
      helpQuestionForm: '个人提问编辑',
      helpQuestionDetail: '个人提问详细',
      helpFaqList: '问答列表',
      helpFaqForm: '问答列表编辑',
      helpFaqDetail: '问答详细',
      articleList: '文章管理',
      articleForm: '文章管理编辑',
      articleDetail: '文章管理详细',
      lotteryRuleList: '抽奖管理',
      lotteryRuleForm: '抽奖管理编辑',
      k3CloudGlVoucherList: '凭证列表',
      k3CloudGlVoucherForm: '凭证录入',
      k3CloudGlVoucherDetail: '凭证详细',
      carrierShopList: '商城门店',
      carrierShopForm: '商城门店编辑',
      carrierProductList: '商城货品',
      carrierProductForm: '商城货品编辑',
      carrierOrderList: '商城订单',
      carrierOrderForm: '商城订单编辑',
      carrierShip: '商城订单发货',
      oppoPlantProductsList: 'OPPO物料编码',
      oppoPlantElectronicList: 'OPPO电子保卡',
      oppoProductsList: 'OPPO颜色编码',
      oppoPlantSendImeList: 'OPPO发货串码',
      vivoPlantProductsList: 'vivo物料编码',
      vivoPlantElectronicList: 'vivo电子保卡',
      vivoProductsList: 'vivo颜色编码',
      vivoPlantSendImeList: 'vivo发货串码',
      productImeStockReport: '库存报表',
      productMonthPriceSum: '保卡统计',
      salaryTemplateList: '工资项目',
      salaryTemplateForm: '工资项目编辑',
      salaryList: '我的工资',
      salaryForm: '我的工资编辑',
      imooPlantProductsList:'Imoo物料编码',
      imooPlantSendImeList:'Imoo发货串码',
      reportCenterTable:'报表中心（表）',
      reportCenterCharts:'报表中心（图）',
      k3cloudCheckOutStock:'出库核对',
      k3cloudCheckOutStockDetail:'出库核对详细',
      cloudSynList:'金蝶核对',
      cloudSynDetail:'金蝶核对详细',
      localizationList:'国际化设置',
      dutyTimeSearchList:'考勤查询',
      employeePointSearchList:'积分查询',
      employeeExpenseList:'费用报销',
      employeeSaleReport:'员工报表',
      productImeUploadReport:'上报报表',
      goodsOrderShipList:'仓库发货',
      productImeSearchList:'串码查询',
      shopAttributeList:'终端统计',
      productImeSaleReport:'销售报表',
      depotInventoryReport:'门店报表',
      b2bForm:'移动订货',
      taskProductTypeList:'任务机型',
      taskAreaList:'办事处任务',
      taskOfficeList:'考核区域任务',
      taskDetailList:'门店任务',
      taskPolicyList:'政策管理',
      areaCommissionList:'办事处提成',
      basicCommissionList:'提成基准',
      priceChangeCommissionList:'调价提成',
      //delete
      hrrecruit:"无效",
      officeUnitsEdit:'单元编辑',
      officeRuleList:'部门规则',
      backendModuleList:'项目模块',
      backendList:'项目管理',
      officeRuleForm:"部门规则编辑",
      backendModuleForm:'项目模块编辑',
      backendForm:'项目管理编辑',
    }
  }
}
