export default {
    reportScoreAreaList: {
        reportScoreAreaList: "Peringkat Kantor Urusan",
        reportScoreOfficeRank: "Ranking penilaian Regional",
        scoreDate: "tanggal",
        officeName: "nama kantor",
        score: "penilaian",
        monthScore: "penilaian bulanan",
        dateRank: "tangal peringkat",
        monthRank: "peringkat bulanan",
        saleQty: "kuantitas penjualan",
        monthSaleQty: "kuantitas penjualan bulanan",
        recentMonthSaleQty: "kuantitas penjualan bulanan belakangan ini",
        point: "inti",
        monthSaleMoney: "uang bulanan",
        pointMonthSaleMoney: "uang bulanan",
        add: "tambah",
        filter: "saring",
        export: "ekspor / mengeluarkan",
        filterOrExport: "saring  / ekspor",
        selectDateRange: "pilih rentang tanggal",
        inputKey: "silahkan masukkan kata kunci",
        inputWord: "silahkan masukkan kata kunci",
        likeSearch: "模糊搜索",
        sure: "yakin",
        loading: "memuat",
        unicode: "kode",
        createdBy: "dibuat oleh",
        createdDate: "tanggal pembuatan",
        lastModifiedBy: "terakhir diubah oleh",
        lastModifiedDate: "terakhir diubah pada tanggal",
        enabled: "diaktifkan / diizinkan",
        locked: "terkunci",
        remarks: "keterangan / komen",
        operation: "operasi / pengerjaan",
        detail: "perincian",
        edit: "ubah",
        delete: "hapus",
        audit: "ubah"
    },
    reportScoreOfficeList: {
        reportScoreOfficeList: "Peringkat Harian",
        officeRank: "peringkat kantor",
        scoreDate: "tanggal",
        officeName: "nama kantor",
        areaName: "area",
        score: "penilaian",
        monthScore: "penilaian bulanan",
        dateRank: "tangal peringkat",
        monthRank: "peringkat bulanan",
        saleQty: "kuantitas",
        monthSaleQty: "kuantitas bulanan",
        recentMonthSaleQty: "kuantitas bulanan belakangan ini",
        point: "inti",
        monthSaleMoney: "uang bulanan",
        pointMonthSaleMoney: "uang bulanan",
        add: "tambah",
        filter: "saring",
        export: "ekspor / mengeluarkan",
        filterOrExport: "saring  / ekspor",
        selectDateRange: "pilih rentang tanggal",
        inputKey: "silahkan masukkan kata kunci",
        inputWord: "silahkan masukkan kata kunci",
        likeSearch: "模糊搜索",
        sure: "yakin",
        loading: "memuat",
        unicode: "kode",
        createdBy: "dibuat oleh",
        createdDate: "tanggal pembuatan",
        lastModifiedBy: "terakhir diubah oleh",
        lastModifiedDate: "terakhir diubah pada tanggal",
        enabled: "diaktifkan / diizinkan",
        locked: "terkunci",
        remarks: "keterangan / komen",
        operation: "operasi / pengerjaan",
        detail: "perincian",
        edit: "ubah",
        delete: "hapus",
        audit: "ubah"
    },
    reportScoreList: {
        reportScoreList: "peringkat harian",
        scoreDate: "tanggal",
        companyScore: "peringkat perusahaan",
        companyMonthScore: "peringkat perusahan bulanan",
        score: "penilaian",
        monthScore: "penilaian bulanan",
        cardQty: "kuantitas kartu",
        monthCardQty: "kuantitas kartu bulanan",
        rank: "peringkat",
        saleQty: "penjualan",
        monthSaleQty: "penjualan bulanan",
        recentMonthSaleQty: "penjualan bulanan belakangan ini",
        saleMoney: "uang bulanan",
        monthSaleMoney: "uang bulanan",
        add: "tambah",
        filter: "saring",
        export: "ekspor / mengeluarkan",
        filterOrExport: "saring  / ekspor",
        selectDateRange: "pilih rentang tanggal",
        inputKey: "silahkan masukkan kata kunci",
        inputWord: "silahkan masukkan kata kunci",
        likeSearch: "模糊搜索",
        sure: "yakin",
        loading: "memuat",
        unicode: "kode",
        createdBy: "dibuat oleh",
        createdDate: "tanggal pembuatan",
        lastModifiedBy: "terakhir diubah oleh",
        lastModifiedDate: "terakhir diubah pada tanggal",
        enabled: "diaktifkan / diizinkan",
        locked: "terkunci",
        remarks: "keterangan / komen",
        operation: "operasi / pengerjaan",
        detail: "perincian",
        edit: "ubah",
        delete: "hapus",
        audit: "ubah"
    },

}