export default{
  salaryList: {
    salaryList: '我的工资',
    add: "添加",
    query: "查询",
    officeName: "部门",
    employeeName: "姓名",
    month: "月份",
    productName: "项目",
    productValue: "值",
    loading: "拼命加载中",
      inputPassword:"请输入用户密码",
      operation: "操作",
  },
  salaryForm:{
    salaryForm:"工资条添加",
    exportTemplate: "导入模板",
    exportData: "导入数据",
    yearMonth: "月份",
    remarks: "备注",
    selectMonth: "选择月份",
    clickUpload: "点击上传",
    uploadImageSizeFor5000KB: "只能上传图片文件，且不超过500kb",
    prerequisiteMessage: "必填信息",
  },
  employeeSalaryBasicList:{
    employeeSalaryBasicList:"工资模板",
    basicSalary:"底薪",
    seniorityWage:"工龄工资",
    reportFee:"报表费",
    socialSecurity:"社保补贴",
    withholding:"代扣",
    deposit:"扣押金",
    id: "编号",
    type: "类型",
    employeeName:"员工",
    shouldGet:"应收",
    effectiveDate:"生效时间",
    processStatus:"状态",
    operation:"操作",
    loading: "拼命加载中",
    edit: "修改",
    delete: "删除",
  },
  employeeSalaryBasicForm:{
    employeeSalaryBasicForm:"工资模板编辑",
    salaryType:"工资类型",
    employeeName:"员工",
    shouldGet:"应得",
    effectiveDate:"生效时间",
    remarks:"备注",
    prerequisiteMessage:"必填信息",
    save:"保存"
  },
  employeeSalaryList:{
    employeeSalaryList:"工资列表",
    add:"添加",
    filter:"过滤",
    loading: "拼命加载中",
    employeeName:"员工",
    month:"月份",
    type:"类型",
    realGet:"实收",
    remarks:"备注",
    edit: "修改",
    delete: "删除",
    operation:"操作",
  },
  employeeSalaryForm:{
    employeeSalaryForm:"工资添加",
    employeeName:"员工",
    type:"类型",
    realGet:"实收",
    month:"月份",
    remarks:"备注",
    save:"保存",
    prerequisiteMessage:"必填信息",
    selectGroup: "请选择分类",
    selectMonth:"请选择月份"
  },
  salaryTemplateList:{
    salaryTemplateList:"工资项目",
    add:"添加",
    loading: "拼命加载中",
    name:"名称",
    salaryTemplateDetailNames:"项目",
    remarks:"备注",
    operation:"操作",
    edit: "修改",
    delete: "删除",
    download:"模板下载"
  },
  salaryTemplateForm:{
    salaryTemplateForm:"工资项目编辑",
    name:"名称",
    remarks:"备注",
    productName:"项目名称",
    sort:"排序",
    delete:"删除",
    save:"保存",
    prerequisiteMessage:"必填信息",
  }
}
