export default {
  companyConfigForm: {
    companyConfigForm: "Preferensi Editor",
    name: "nama",
    code: "kode",
    value: "angka",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan/komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  companyConfigList: {
    companyConfigList: "Pengaturan parameter",
    id: "ID",
    name: "nama",
    code: "kode",
    value: "angka",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  officeForm: {
    officeForm: "formulir kantor",
    parentId: "atasan",
    officeName: "nama",
    type: "jenis",
    jointType: "tipe",
    point: "inti",
    taskPoint: "inti pekerjaan",
    sort: "pengurutan",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang harus diisi",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  officeList: {
    officeList: "daftar kantor",
    parentName: "nama",
    name: "nama",
    typeLabel: "jenis label",
    dingId: "kode",
    point: "inti",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring  / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "PENCARIAN",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "ubah"
  },
  officeChangeList:{
    add: "tambah",
    filter: "saring",
      batchPass:"批量通过",
      batchBack:"批量打回",
    id: "ID",
    type:"TIPE",
    officeName:"部门",
    oldLabel:"sebelum modifikasi",
    newLabel:"sesudah modifikasi",
    processStatus:"status proses",
    operation:"operasi / pengerjaan",
    sure: "yakin",
      detail:"详细",
      delete:"删除",
      edit:"修改",
    selectGroup: "pilih grup",
    createdDate: "tanggal pembuatan",
  },
  officeChangeForm:{
    search:"搜索",
    save:"simpan",
    stockNumber:'机构名称',
      oldPoint:"总旧点位",
      newPoint:"总新点位",
  },
  dictEnumForm: {
    dictEnumForm: "Enum Kamus Editor",
    category: "klasifikasi / kategori",
    sort: "pengurutan",
    value: "angka",
    selectGroup: "请选择分类",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  dictEnumList: {
    dictEnumList: "pencacahan kamus",
    id: "ID",
    category: "klasifikasi / kategori",
    value: "angka",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "PILIH TANGGAL",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  dictMapForm: {
    dictMapForm: "Key Kamus Editor",
    category: "klasifikasi / kategori",
    selectCategory: "pilih kategori",
    name: "nama",
    value: "angka",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  dictMapList: {
    dictMapList: "Kamus kunci",
    id: "ID",
    category: "klasifikasi / kategori",
    value: "angka",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa",
  },
  folderFileList: {
    folderFileList: "Manajemen File",
    id: "ID",
    folderName: "nama folder",
    name: "nama",
    contentType: "jenis",
    size: "ukuran",
    add: "tambah",
    filter: "saring",
    export: "saring / ekspor",
    filterOrExport: "过滤OR导出",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  folderForm: {
    folderForm: "mengedit direktori file",
    parentId: "induk",
    selectGroup: "pilih grup",
    name: "nama",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  folderList: {
    folderList: "daftar folder",
    name: "nama",
    add: "tambah",
    filter: "saring",
    export: "saring / ekspor",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa",
  },
  menuCategoryForm: {
    menuCategoryForm: "mengubah pilihan grup",
    name: "nama",
    sort: "pengurutan",
      backendModuleId:"所属模块",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    prerequisiteMessage: "Informasi yang diperlukan",
  },
  menuCategoryList: {
    menuCategoryList: "daftar kategori pilihan",
    code:"code",
    name: "nama",
    backendModuleCode:"所属模块",
    backendModuleName:"所属模块名称",
    sort: "pengurutan",
    add: "tambah",
    filter: "saring",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    edit: "ubah",
    delete: "hapus",
  },
  menuForm: {
    menuForm: "formulir pilihan",
    menuCategory: "pilihan kategori",
    category: "kategori",
    name: "nama",
    code: "code",
    sort: "pengurutan",
    href: "link",
    mobile: "telepon",
    visible: "pameran",
    permissionStr: "izin",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    selectGroup: "请选择分组",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  menuList: {
    menuList: "daftar menu",
    id: "ID",
    name: "nama",
    category: "kategori",
    menuCategoryName: "pengelompokan",
    sort: "pengurutan",
    href: "Link",
    mobile: "menu telepon",
    menuCategoryId:"一级菜单",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  permissionForm: {
    permissionForm: "formulir perizinan",
    menu: "pilihan",
    selectCategory: "pilih kategori",
    name: "nama",
      roleIdList:"角色",
      permission: "perizinan",
    position: "posisi",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  permissionList: {
    permissionList: "IZIN",
    name: "nama",
    permission: "PERIZINAN",
    menuName: "NAMA",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa",
  },
  processList: {
    processList: "DAFTAR PROSES",
    id: "ID",
    deploymentId: "nomor versi",
    name: "nama",
    key: "KEY",
    version: "versi",
    resourceName: "XML",
    deploymentTime: "waktu penyebaran",
    suspended: "apakah tertunda",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  processTypeForm: {
    processTypeForm: "Proses Editor dinamis",
    name: "NAMA",
    createdPositionIds: "drafting Izin",
    viewPositionIds: "Lihat izin",
    auditFileType: "periksa berkas",
    sort: "pengurutan",
    positionName: "nama posisi",
    selectPositionName: "pilih nama posisi",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    operation: "操作",
    sure: "yakin",
    delete: "删除",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "Informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  processTypeList: {
    processTypeList: "DAFTRA TIPE PROSES",
    id: "ID",
    name: "NAMA",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "pilih rentang tanggal",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "diubah oleh",
    createdDate: "diubah pada tanggal",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diizinkan",
    locked: "terkunci",
    remarks: "eterangan / komen",
    operation: "operasi",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  backendForm: {
    backendForm: "backend Kamus Editor",
    code:"code",
    name: "nama",
    remarks: "keterangan / komen",
    save: "simpan",
    prerequisiteMessage: "informasi yang diperlukan",
  },
  backendList: {
    backendList: "pencacahan kamus",
    id: "ID",
    name: "nama",
    code:"code",
    add: "tambah",
    filter: "saring",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    edit: "ubah",
    delete: "hapus",
  },
  backendModuleForm: {
    backendModuleForm: "backendModule Kamus Editor",
    code:"code",
    name: "name",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang diperlukan",
    inputLegalValue: "silahkan masukkan angka yang valid"
  },
  backendModuleList: {
    backendModuleList: "pencacahan kamus",
    id: "ID",
    code:"code",
    name: "nama",
    backendName:"项目名称",
    add: "tambah",
    filter: "saring",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "PILIH TANGGAL",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa"
  },
  officeRuleForm: {
    officeRuleForm: "部门规则编辑",
    name: "name",
      code:"Code",
      parentId:"上级",
      hasPoint:"是否有点位",
    remarks: "keterangan / komen",
    sure: "yakin",
    save: "simpan",
    filter: "saring",
    prerequisiteMessage: "informasi yang diperlukan"
  },
  officeRuleList: {
    officeRuleList: "部门规则列表",
    id: "ID",
    name: "nama",
    add: "tambah",
    filter: "saring",
      code:"Code",
      parentName:"上级",
      hasPoint:"是否有点位",
    export: "ekspor / mengeluarkan",
    filterOrExport: "saring / ekspor",
    selectDateRange: "PILIH TANGGAL",
    inputKey: "silahkan masukkan kata kunci",
    inputWord: "silahkan masukkan kata kunci",
    likeSearch: "pencarian",
    sure: "yakin",
    loading: "memuat",
    unicode: "kode",
    createdBy: "dibuat oleh",
    createdDate: "tanggal pembuatan",
    lastModifiedBy: "terakhir diubah oleh",
    lastModifiedDate: "terakhir diubah pada tanggal",
    enabled: "diaktifkan / diizinkan",
    locked: "terkunci",
    remarks: "keterangan / komen",
    operation: "operasi / pengerjaan",
    detail: "perincian",
    edit: "ubah",
    delete: "hapus",
    audit: "periksa",
    business:"业务部门",
    support:"后勤部门"
  },
    roleList:{
        name:"名称"
    },
    roleForm:{
        name:"名称",
        permission:"权限",
        remarks:"备注",
        save:"保存",
        moduleIdList:"授权",
        prerequisiteMessage:"必填信息"
    }
}
